### ISSUE TITLE
slow performance using Ruby Enterprise Edition 1.8.7

### ISSUE THREAD

**Issue by bmishkin** [wvanbergen/request-log-analyzer#101]
I am getting really bad performance using request-log-analyzer (v1.11.0) to analyze rails files for a specific application. Typical file size is ~15MB, and it takes > 15 minutes to run (using ree-1.8.7). It also uses 100% of a cpu core during the run, not great for a production server!

I pulled down a log file to my local machine and ran request-log-analyzer using stock ruby-1.8.7 - it ran in about 8 seconds, as expected. When I switched to ree-1.8.7, similar to performance on the server it took > 10 minutes. 

I saw in the release notes that request-log-analyzer has been tested using REE (1.10.1). Has anyone tested the performance of r-l-a with REE? Anyone else experiencing slow performance analyzing logs using REE?

For a sample 866k log file:

<pre>
ruby 1.8.7 (2010-04-19 patchlevel 253) [i686-darwin10.7.0], MBARI 0x6770, Ruby Enterprise Edition 2010.02
real    0m21.148s
user    0m20.888s
sys     0m0.225s

ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
real    0m1.706s
user    0m1.338s
sys     0m0.224s
</pre>

As you can see, > 10X slower performance with REE. I tested it on multiple log files for this app on multiple platforms.

When I tested a different application's logs, I did not see an appreciable difference between REE and stock ruby. So there is something in the combination of one of my apps w/ REE 1.8.7 that causes r-l-a to run slowly. I do use subdomains in that app, perhaps that's the problem?

Any help appreciated!

--Ben

**Comment by barttenbrinke** [comment]
Hi Ben,

Running my 40MB testset I get:
- ruby-1.8.7-head - 27 secs
- ree-1.8.7-2011.03 - 23 secs

so probably the ruby isn't to blame. RLA normally has two bottlenecks: Disk i/o & CPU.. the ruby version should not have an impact of 10x.

What happens if you run your test log locally with REE and with Ruby-1.8.7 and what happens if you run the same on your server? Is the server physical or virtual?

**Comment by bmishkin** [comment]
The server is a 64-bit EC2 instance (virtual). But i'm certain it's not a server / hardware / OS issue. 

I ran the test log locally using REE and ruby-1.8.7 (via rvm), and saw the same slow performance with REE compared to stock ruby. Then I ran a test log from a different app locally using REE, and did not see the performance difference. So it must be the combination of REE + my app.

This app uses rails 2.3.2 (unfortunately). Maybe there's something unique about the way rails 2.3.2 outputs log info?

**Comment by bmishkin** [comment]
I am by no means a ruby-prof expert. But running a 866k log file locally using REE (which took ~26 sec) with ruby-prof shows

<pre>
Thread ID: 2148444460
Total: 25.754731

 %self     total     self     wait    child    calls  name
 75.92     19.55    19.55     0.00     0.00    29657  Regexp#=~
  7.69      5.76     1.98     0.00     5.63    30464  Array#each
...
</pre>

**Comment by barttenbrinke** [comment]
Could you email me the logfragment you are testing with?
If I get the same, i'll contact the guys from Phusion and see if they know what is going on.
