### ISSUE TITLE
More than one output not possible

### ISSUE THREAD

**Issue by sodoku** [wvanbergen/request-log-analyzer#102]
It does not seem to be possible to have two output options at the same time.
I want the analyzed data to be sent per mail _and_ saved as html. Running the analyzer twice is not an option as all data will be analyzed twice too.

**Comment by bratke** [comment]
this affects me too

**Comment by barttenbrinke** [comment]
Aha, well technically this should not be that hard, as we will just need support for an array of outputs instead of a single one.
