### ISSUE TITLE
undefined method 'class_inheritable_accessor'

### ISSUE THREAD

**Issue by simonbaumer** [wvanbergen/request-log-analyzer#103]
I created a new app that contained version 1.11.1 in the Gemfile. Bundle installed, fired up the server and tried running:
$ request-log-analyzer -d request.db log/production.log

And it threw the following error:
/Users/usernamehere/.rvm/gems/ruby-1.8.7-p352/gems/activerecord-3.1.0/lib/active_record/base.rb:1082:in `method_missing': undefined method`class_inheritable_accessor' for RequestLogAnalyzer:atabase::Base(abstract):Class (NoMethodError)

I tried with both Rails 3.1.0 and Rails 3.0.10, both gave the error. When I run just '$ request-log-analyzer log/production.log' it runs successfully, but couldn't save it to sqlite DB. I also tried the --database options flag instead of -d, same error.

**Comment by wvanbergen** [comment]
I think class_inheritable_accessor needs to change to class_attribute in the latest Rails/ActiveRecord version. That will break compatibility with old Rails versions though.

**Comment by wvanbergen** [comment]
@barttenbrinke What do you think?

**Comment by nitsujri** [comment]
+1 for issue with me, Rails 3.1.

When I fix that line I run:

request-log-analyzer --format rails3 -d requests.db production.log

Then I get:

connection_pool.rb:409:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)

request_log_analyzer/aggregator/database_inserter.rb:40:in `block in aggregate'

if there's anything I can do to help. Thanks guys this gem has helped me a lot!

---

request-log-analyzer --format rails3 -d requests.sqlite production.log
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.11.1
Website: http://railsdoctors.com

/Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:409:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/connection_adapters/abstract/connection_specification.rb:107:in`retrieve_connection'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/connection_adapters/abstract/connection_specification.rb:89:in `connection'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:75:in`connection'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:54:in `initial_count_for'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:12:in`block in initialize'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:29:in `yield'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:29:in`default'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:29:in `aliased_name_for'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/alias_tracker.rb:17:in`aliased_table_for'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/join_helper.rb:15:in `block in construct_tables'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/join_helper.rb:14:in`each'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/join_helper.rb:14:in `construct_tables'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association_scope.rb:49:in`add_constraints'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association_scope.rb:33:in `scope'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association.rb:99:in`association_scope'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association.rb:88:in `scoped'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/collection_association.rb:437:in`create_scope'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association.rb:238:in `block in build_record'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/base.rb:1569:in`initialize'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/reflection.rb:190:in `new'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/reflection.rb:190:in`build_association'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/association.rb:236:in `build_record'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/collection_association.rb:104:in`build'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.1/lib/active_record/associations/collection_proxy.rb:54:in `build'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/aggregator/database_inserter.rb:40:in`block in aggregate'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/aggregator/database_inserter.rb:36:in `each'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/aggregator/database_inserter.rb:36:in`aggregate'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/controller.rb:314:in `block in aggregate_request'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/controller.rb:314:in`each'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/controller.rb:314:in `aggregate_request'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/controller.rb:335:in`block in run!'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:327:in `handle_request'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:291:in`update_current_request'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:220:in `parse_line'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:177:in`parse_io_19'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:127:in `block in parse_file'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:127:in`open'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:127:in `parse_file'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/source/log_parser.rb:77:in`each_request'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/lib/request_log_analyzer/controller.rb:333:in `run!'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/gems/request-log-analyzer-1.11.1/bin/request-log-analyzer:126:in`<top (required)>'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/bin/request-log-analyzer:19:in `load'
    from /Users/justinlouie/.rvm/gems/ruby-1.9.2-p290/bin/request-log-analyzer:19:in`<main>'

**Comment by barttenbrinke** [comment]
Please see #104
