### ISSUE TITLE
Allow parsing of compressed log files

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#11]
Allow parsing compressed files. This can be auto-detected using the filename extension, e.g. .gz.

Maybe it is possible to decompress the file in small parts, in order to keep the memory usage down. Otherwise, the files can be decompressed into a temporary file.

**Comment by barttenbrinke** [comment]
Do we really want to do this? The idea of linux tools is that they do 1 thing and they do it good. You could just pipe a tar.gz file trough tar and through rla, right? Maybe add an example of this to the examples.

**Comment by wvanbergen** [comment]
That approach does not work if you want to parse multiple files at once (production.3000.log.gz, production.3001.log.gz, etc.)

**Comment by wvanbergen** [comment]
Of course, .bz2 and maybe .zip files could be supported as well.

**Comment by barttenbrinke** [comment]
Sombody agrees with me :) : http://snippets.aktagon.com/snippets/245-How-to-unzip-gunzip-untar-files-with-Ruby

**Comment by barttenbrinke** [comment]
Just calling the system util would be pretty acceptable I guess..

**Comment by barttenbrinke** [comment]
Added basic gz, bz2 and zip support to master. Needs specs + checking :).

**Comment by barttenbrinke** [comment]
The progress bar is not working for gzipped files, but as the decompressors just dump a single string as stdout, this is not an easy fix, so I've closed this ticket. Specs are also added for gz tgz zip and bz2. We need release notes :)
