### ISSUE TITLE
Do not change Encoding.default_external

### ISSUE THREAD

**Issue by eregon** [wvanbergen/request-log-analyzer#110]
Hello,

The commit https://github.com/wvanbergen/request-log-analyzer/commit/b777252b73f36e486e4a93a756c587b624376f56 seems very wrong to me as it modify global state and may alter other libraries behavior.

If this is a fix for Rails, the problem should be solved in Rails. If it is for request-log-analyser itself, it should not be needed and things like 'b' mode should be used instead.

I met this problem today while running alf specs with ruby-trunk.
Let me explain what I did to find out the problem:
- The spec failing was about yaml output, which showed a base64 binary String.
- So I looked at YAML and figured it was somewhere else.
- I figured it's somehow linked to the CSV library (by looking who use String#force_encoding).
- The CSV library might use #force_encoding if the output is binary, which is the case on ruby-trunk now because 1) Encoding.default_external was changed and 2) on ruby-trunk StringIO.read might return a binary string.

That latter behavior might seem weird, but it's actually logical. If you are telling ruby that all external resources (such as CSV files) are binary, the result String should have a binary encoding.

So, could you please remove that global state change?

**Comment by barttenbrinke** [comment]
As the commit was made to fix a specific problem (rails 2.2 with color coding in production), this fix probably isn't that relevant anymore to begin with. Next to the fact that it does indeed change the global state, I see no reason not to remove it. Willem, do you have a different look on this?

**Comment by Narnach** [comment]
A clean solution would be to replace all File.open calls with calls that specify open mode BINARY to stay backwards compatible with Rails 2.2. That way the global state change can go and functionality remains preserved.

**Comment by barttenbrinke** [comment]
There is only 1 instance where the file is read: log_parser.rb - parse_file (line 117). But I'm somewhat confused as to why the original problem occurs at all. Why does the rails2.2 logfile have a strange encoding format and why wont Ruby 1.9 just read it?

**Comment by wvanbergen** [comment]
The old Rails logger would always log the values of all the parameters. Given that hey can come from different sources, the log file ends up containing a mixture of encodings. This cannot be read properly by Ruby 1.9, and it will raise an encoding exception.

The solution would indeed be reading the file using `File.open(name, 'rb')`. However, we should still be careful in these situations for Ruby 1.9, because running a regex on a string will implicitly convert it to unicode. In that case, the encoding error can still occur and should be rescued properly.

Ideally, we would have a sample file that triggers this error so we can build a test for it.

**Comment by barttenbrinke** [comment]
Isn't a sample containing a broken utf8 form submission and a correct one good enough? Like this:

Started POST "/login" for 123.123.123.200 at Mon Feb 27 08:32:02 +0100 2012
Processing by UsersController#login as HTML
  Parameters: {"commit"=>"Sign in", "username"=>"example.user", "authenticity_token"=>"bsEw5knkerILvHM+x/tsaKARTkV9qBWDZ9W+nV31BA=", "utf8"=>"\342\234\223", "password"=>"[FILTERED]"}
Redirected to https://exampleapp.com/
Completed 302 Found in 158ms (ActiveRecord: 138.5ms)

Started POST "/login" for 123.123.123.100 at Mon Feb 27 08:45:12 +0100 2012
Processing by UsersController#login as HTML
  Parameters: {"commit"=>"Sign in", "username"=>"b.gates", "authenticity_token"=>"1Zg5yhe46xjxwrqJ4WYhfCByLB4cKyQmLkxokJJONgs=", "utf8"=>"✓", "password"=>"[FILTERED]"}
  Redirected to https://exampleapp.com/
Completed 302 Found in 10ms (ActiveRecord: 4.5ms)

**Comment by barttenbrinke** [comment]
Apperantly this is not enough to reproduce the problem under 1.9.1..

**Comment by wvanbergen** [comment]
Nope, because the data is escaped it is just ASCII. You need to include the actual contents of a file upload.

**Comment by eregon** [comment]
@barttenbrinke I think you can ignore 1.9.1, it's well known to have many problems, notably with encoding, and it's now deprecated.

**Comment by barttenbrinke** [comment]
Okay, then we still need someone to supply us with logfile that fails when the force_encoding  is removed. Have you got an old log somewhere, @Narnach ? #edit because of stupid phone autocorrect

**Comment by barttenbrinke** [comment]
After checking: The "just read binary" fix was allready done by @wvanbergen on 2010-01-28: https://github.com/wvanbergen/request-log-analyzer/commit/3031050ad4c5eb88befcc2a5965c28b656242b5e . This is an improvement on the fix from @Narnach on 2009-06-21 and explains why I am unable to reproduce the problem when I remove the global Encoding setting on my test environment. Therefore the line can be removed, without causing any backwards compatibility issues. The Regexp issue stands, but is not relevant to this issue. I just removed the Encoding lines from master.

**Comment by eregon** [comment]
Thanks for the fast reaction and fix!
