### ISSUE TITLE
Installation warning (Ruby 1.9.3) 

### ISSUE THREAD

**Issue by kathgironpe** [wvanbergen/request-log-analyzer#111]
<pre>
Installing ri documentation for request-log-analyzer-1.12.2...
unable to convert U+2501 from UTF-8 to US-ASCII for lib/request_log_analyzer/output/fixed_width.rb, skipping

</pre>

It's just a warning but the gem seems to be working.

**Comment by wvanbergen** [comment]
This is caused by RI not being able to deal with UTF characters. 

You can safely ignore this warning. Personally, I never use RI documentation, so I disabled building it in my Rubygems configuration completely.
