### ISSUE TITLE
Executing the 'console' command results in 'require:LoadError'

### ISSUE THREAD

**Issue by bradland** [wvanbergen/request-log-analyzer#113]
Executing a command like the one below results in a load error.

```
$ request-log-analyzer console --database production.sqlite --format rails3
/Users/bradland/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':LoadError: cannot load such file -- ./lib/cli/database_console_init
```

I know the database functionality is really low priority right now, but the fix is very simple, and shouldn't affect older Ruby versions because the load path is correctly adjusted in `bin/request-log-analyzer` on line 4. I'm going to submit a pull request in just a few minutes.

**Comment by barttenbrinke** [comment]
If people fix their own bugs for us, we are always willing to accept a pull request :)! Thanks!

**Comment by barttenbrinke** [comment]
I'll just fix travis-ci & then I will push out a new release.

**Comment by bradland** [comment]
Glad to help. I'm so grateful for this tool.
