### ISSUE TITLE
Identify Server in Output

### ISSUE THREAD

**Issue by asanghi** [wvanbergen/request-log-analyzer#117]
Your gem is awesome. It's an awesome gem of a gem. I use it on more than one server where I get them to email me the results daily and I've used it like that for a while now.

A small irksome thing I find is that I'm a bit confused which server the email has come from (production/staging) or a completely different app (results do tell of course). 

I was wondering if we could add our own special tag like server name / app name in the header of the body of the email that gets sent?

If you like the idea or want to suggest a different solution, I can help send a patch request if needed.

Cheers,
Aditya

**Comment by barttenbrinke** [comment]
Hi Asanghi,

you can use the `mailsubject` option to specify the hostname you are running from.
Would that solve your problem?

```
request-log-analyzer --mailsubject `whoami` --mail alfa@beta.com
```

**Comment by asanghi** [comment]
Sure! Does that override the current existing subject or augment it? I'd only like to augment it. But Yes I think it would suffice for now.

**Comment by barttenbrinke** [comment]
That overwrites the current subject, but as the current implementation does:

```
      subject       = @options[:subject]     || "Request log analyzer report - generated on #{Time.now.to_s}"
```

You should be able to do something like this:

```
request-log-analyzer --mailsubject "`whoami`: Request log analyzer report - generated on `date`" --mail alfa@beta.com
```

Or add some other bash voodoo in there.

**Comment by asanghi** [comment]
Thanks heaps! Closing!
