### ISSUE TITLE
Rails project integration brainstorm

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#12]
We could improve integration with a Rails project. This tickets contains some ideas to accomplish this:
## Settings
- Request database connection in config/database.yml (see also #10). This way, it could even be accessed from the rails application itself :-)
- Store settings in config/rla.yml
- Store log filename pattern per environment in settings file (e.g. production.*.log.gz) 
## Rake tasks
- <code>rla:report</code> Run rla on and return ASCII report in terminal
- <code>rla:report:html</code> Run rla and create a HTML report
- <code>rla:report:yaml</code> Run rla and create raw YAML report (se #13)
- <code>rla:database</code> Parse request log and store requests in database
- <code>rla:database:reset</code> Clear the request database
## Other ideas
- Archive reports (with date in filename) on a default location so comparisons are possible (e.g. /doc/performance)
- Run r-l-a as cronjob?

**Comment by barttenbrinke** [comment]
rla:report and rla:report:html are allready there.

**Comment by wvanbergen** [comment]
Separated out config file to separate issue (see #16)

**Comment by wvanbergen** [comment]
All this stuff will be for Rails 3.0 only. Moreover, this may only be implemented in request-log-analyzer 2.0 as a plugin, because it is outside the scope of the basic application. I've opened a separate 2.0 issue for this.
