### ISSUE TITLE
Inclusion of Log File's path in output

### ISSUE THREAD

**Issue by asanghi** [wvanbergen/request-log-analyzer#122]
So earlier I raised an issue with inclusion of server name or some identifier in the email. That kinda sorta didnt work because the backticks got escaped by whenever gem. I'd have to schedule logging outside of my rails app which is slightly ugh.

Anyway, It would be really nice if the full path of log file being analyzed was listed in the out (html)

Hard? Want pull request?

**Comment by barttenbrinke** [comment]
Pull requests are always welcome and I think so far we've never not pulled one :)

**Comment by asanghi** [comment]
They way it is engineered, it aggregates across one or more files so reporting one file would be tricky! 

I can see you've got some code to trigger source changes. Perhaps the summarizer can track the files which have been used and report a table with source files?

How about that? I think I've got the hang of it but maybe call upon you for some help.

**Comment by barttenbrinke** [comment]
Please just try your best, get the test passing and then submit a pull request. Then it would be a lot easier to discuss if the changes you made are okay or that they need some cleaning up.

**Comment by asanghi** [comment]
Thanks! I think I did it! My editor keeps removes stray white space, hope you dont mind.

https://github.com/wvanbergen/request-log-analyzer/pull/123
