### ISSUE TITLE
Multi-thread process

### ISSUE THREAD

**Issue by tuannvm** [wvanbergen/request-log-analyzer#128]
I have run it to parse 2GB log file. I noticed that your program only use 1 cpu to run (single thread). So how can we make it multi-thread? So please give me an idea about that.

Thanks you!

**Comment by barttenbrinke** [comment]
Have you tried using JRuby or Rubinius?

**Comment by barttenbrinke** [comment]
We have had an experimental branch doing the teaser checker in parallel, but for something like NGINX this probably won't help.

**Comment by tuannvm** [comment]
I used JRuby. About nginx, I just modified some option in apache log format and it works. RLA took 5 minutes to parse 2GB log file with single-thread mode, so I think multi-thread will significantly speed up time.

Thanks you!

**Comment by barttenbrinke** [comment]
JRuby should be using more than one core to do the Regexp's, so that is a bit strange. The inherent problem is that you are going through a log file linearly and splitting that up into parallel tasks is not trivial.

**Comment by barttenbrinke** [comment]
Also, could you post the modification you are using? I'd like to add NGINX support to request-log-analyser

**Comment by barttenbrinke** [comment]
The experimental branch is still here: https://github.com/wvanbergen/request-log-analyzer/tree/multithreaded

**Comment by tuannvm** [comment]
Here is my nginx log_format:
$remote_addr [$time_local] $host $remote_user "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $upstream_respond_time';
Andy my modification in file_format/apache.rb:
LOG_FORMAT_DEFAULTS = {
      :common   => '%h %l %u %t "%r" %>s %b',
      :combined => '%h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-agent}i"',
      :rack     => '%h %l %u %t "%r" %>s %b %T',
      :referer  => '%{Referer}i -> %U',
      :agent    => '%{User-agent}i' ,
      :nginx    => '%a %t %h %u "%r" %>s %b' 
    }
analyze.frequency :category => :remote_ip, :title => "Most IP request"    if line_definition.captures?(:remote_ip)

# add support for most IP request.

I have played with multi-thread brand, now I can parse log with more than one cpu process at time. But interrupt with Ctrl + C is not worked like master brand. Try to figure out how to fix that.

Thanks you!

**Comment by barttenbrinke** [comment]
But... is it also faster :)?

**Comment by tuannvm** [comment]
Not really :) I hope that it's X times faster with X CPUs. But it seems like sharing the load over each CPU, which means all CPUs do the same job at the same time.
One more thing. Is it impossible to interrupt (Ctrl+C) multi-thread process?

**Comment by barttenbrinke** [comment]
That should just work as it is sending an interrupt. Do you have an example?
