### ISSUE TITLE
Nothing on the Sample output wiki page?

### ISSUE THREAD

**Issue by holyjak** [wvanbergen/request-log-analyzer#132]
The [Sample output wiki page](/wvanbergen/request-log-analyzer/wiki/Sample-output) is empty while it should contain example output of the tool.

**Comment by barttenbrinke** [comment]
Somehow it has gone missing :) Feel free to post an example run of rails 3 in there, if you have one that is interresting.

**Comment by holyjak** [comment]
I do not :(
Den 28. jan. 2013 13:00 skrev "Bart ten Brinke" notifications@github.com
følgende:
