### ISSUE TITLE
write to mysql database?

### ISSUE THREAD

**Issue by timsmith00** [wvanbergen/request-log-analyzer#133]
Are there any plans to add the ability to write the output directly to mysql (or other) database versus just writing to a sqlite db/ text file?

**Comment by barttenbrinke** [comment]
Hello Tim,

it is currently possible to store the analyzed data into a database by using the database inserter. It is currently not possible to to do this directly from Rails.

**Comment by wvanbergen** [comment]
Request-log-analyzer supports all databases that are supported by ActiveRecord.

You can specify the database connection as a URI or as an ODBC connecting string:
- `mysql://username@localhost.local/database`
- `adapter=sqlite3;database=filename.db`

**Comment by timsmith00** [comment]
Thank you for the follow-up, very cool.  That that I re-read my question, I appreciate your comment barttenbrinke - what I meant to ask was is it possible to specific a mysql database on the command line - use mysql versus a sqlite database.

I am somewhat new to ruby & rails.  Its ok if it scrapes the log files, I just want to write its output to a mysql database versus a sqlite database.  So wvanbergen, are you saying that I can use a yaml file that I pass from the command line or is that a gem configuration option?

**Comment by wvanbergen** [comment]
You can pass a string like I mentioned above to the `--database` command line argument.
