### ISSUE TITLE
Errno errors ignored in rails logs

### ISSUE THREAD

**Issue by depquid** [wvanbergen/request-log-analyzer#136]
The regexes for matching exception classes in rails logs require the class name to have a lowercase letter.  However, exception classes in the Errno module are all uppercase.  For example:

```
Errno::EACCES (Permission denied - /tmp/test_file)
```

Such lines are not reported by request-log-analyzer as failed requests, even though such errors tend to be quite severe.  Would modifying the regexes to allow all these uppercase names to match work?  I don't know how well-defined exception lines are or whether such changes to the regexes could result in incorrectly matching other lines.

**Comment by barttenbrinke** [comment]
Rails will continue to render a 500 after this, which will be analyzed by the Request-log-Analyzer. As the exception will just be blurted into the log file, I don't really see a correct way to tie them back to the original request causing the error.

**Comment by wvanbergen** [comment]
We can probably tweak the regex a bit.

The problem with exception lines is they are very unstructured, and making the regex too liberal will make it match lines that it shouldn't. So we have to be careful.

**Comment by depquid** [comment]
@barttenbrinke Such 500 errors are not shown in the "Failed requests" section of the report on my system.  Admittedly, I am using Rails 2.3.5 (I know...), so I don't know if it would work with later versions.  Is that version unsupported?

@wvanbergen I understand the difficulties with making the regex too liberal, which is why I didn't want to just submit a patch without first trying to understand more about how the current regex was chosen.

Of course, a safer, albeit less elegant, way to modify the regex is to provide for the Errno cases explicitly:

```
((?:[A-Z]\w*[a-z]\w+\:\:)*[A-Z]\w*[a-z]\w+|Errno\:\:[A-Z]\w+)
```

**Comment by barttenbrinke** [comment]
That would work, but then it still would not be possible to tie it back to the original request.
