### ISSUE TITLE
Add --email options to email the results

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#14]
This may be useful when used with a cronjob to do periodical analysis on an application's logs. Adding an example cronjob would be nice as well for reference.

**Comment by wvanbergen** [comment]
Maybe we can use Pony (http://adam.blog.heroku.com/past/2008/11/2/pony_the_express_way_to_send_email_from_ruby/)? Pony can send using sendmail or smtp. It does require TMail however, so we would add two dependencies for this feature.

If we would simply use (command line) sendmail for sending the email, we can implement it without dependencies. This will not work on Windows however.

**Comment by barttenbrinke** [comment]
I'd rather do this: simpler and more crossplatform:
http://snippets.dzone.com/posts/show/2362

**Comment by wvanbergen** [comment]
Is localhost usable as SMTP server on every platform?

**Comment by barttenbrinke** [comment]
Let them specify a host if they want to use a different one. Most server environemnts will have either mailing from localhost or something like a mail.internal host.

**Comment by barttenbrinke** [comment]
```
def send_email(to, message, host = 'localhost')
msg = <<END_OF_MESSAGE
From: #{from_alias} <#{from}>
To: #{to_alias} <#{to}>
Subject: #{subject}

#{message}
END_OF_MESSAGE

  Net::SMTP.start(host) do |smtp|
    smtp.send_message msg, from, to
  end
end
```

**Comment by wvanbergen** [comment]
What about Windows? Moreover, most server environments also have sendmail (or a drop-in replacement) installed. Using the sendmail binary, we would not have to add the NET::SMTP dependency.

**Comment by barttenbrinke** [comment]
NET::STMP works on windows, if you specify the SMTP host. And we could just require Net::STMP  when needed. Is it part of default ruby? backticking mail seems a bit ugly when replacing just a single command.

**Comment by barttenbrinke** [comment]
a1f8c26..56c91fb  master -> master

**Comment by wvanbergen** [comment]
Nice work (y)
