### ISSUE TITLE
Custom file format subclass fails with Invalid file format! (RuntimeError)

### ISSUE THREAD

**Issue by markpaine** [wvanbergen/request-log-analyzer#142]
Seems that line_definitions from the superclass aren't being merged with those of the subclass any longer, so valid_line_definitions? thinks that there's no header or footer, given the following.

class LogLineFormat < RequestLogAnalyzer::FileFormat::Rails3
  line_definition :api_call do |line|
    line.regexp = /Required ([0-9]+)ms to ([A-Z]+) /
    line.captures << { :name => :api_call_duration, :type => :duration, :unit => :msec } \
                  << { :name => :api_call_verb, :type => :string }
  end
  report(:append) do |analyze|
    analyze.frequency :api_call_verb, :title => "API call verbs", :line_type => :api_call
    analyze.duration :api_call_duration, :title => "API call duration", :category => :api_call_verb
  end
end

**Comment by barttenbrinke** [comment]
Did you get this problem when you updated to the latest release? Because we did some major refactoring and we might have broken something here regarding subclassing.

**Comment by markpaine** [comment]
I'm on Github master. I saw the commit of pair of commits which look to be
the likely culprit but haven't had a chance to dig deeper.

Thanks
Mark

**Comment by sanemat** [comment]
I have same problem, custom file format does not work.

```
$ cat search.rb 
class Search < RequestLogAnalyzer::FileFormat::Rails3
end

$ bundle exec request-log-analyzer production.log --format search.rb
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.12.9
Website: http://railsdoctors.com

/Users/sane/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:252:in `initialize': Invalid file format! (RuntimeError)
        from /Users/sane/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:187:in `new'
        from /Users/sane/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:187:in `build'
        from /Users/sane/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/request-log-analyzer-1.12.9/lib/request_log_analyzer/controller.rb:92:in `build_from_arguments'
        from /Users/sane/.rbenv/versions/1.9.3-p429/lib/ruby/gems/1.9.1/gems/request-log-analyzer-1.12.9/bin/request-log-analyzer:129:in `<top (required)>'
        from /Users/sane/.rbenv/versions/1.9.3-p429/bin/request-log-analyzer:23:in `load'
        from /Users/sane/.rbenv/versions/1.9.3-p429/bin/request-log-analyzer:23:in `<main>'
```

**Comment by sanemat** [comment]
In my custom format, `@line_definitions` and `@report_trackers` is empty:

```
source.file_format
=> #<Search:0x007f909483df98 @line_definitions={}, @report_trackers=[]>
```

No given format, then:

```
source.file_format
=> #<RequestLogAnalyzer::FileFormat::Rails:0x007fa42250c9b8
 @line_definitions=
  {:processing=>
    #<RequestLogAnalyzer::LineDefinition:0x007fa422357eb0
     @captures=
      [{:name=>:controller, :type=>:string},
       {:name=>:action, :type=>:string},
       {:name=>:format, :type=>:string, :default=>"html"},
       {:name=>:ip, :type=>:string},
       {:name=>:timestamp, :type=>:timestamp},
       {:name=>:method, :type=>:string}],
     @compound=[],
     @header=true,
     @name=:processing,
     @regexp=
```

**Comment by alecnmk** [comment]
same here v1.13.0

**Comment by barttenbrinke** [comment]
Ok: Trackers and definitions get created when calling .create on a class.

```
RequestLogAnalyzer::FileFormat.load(:rails3) calls RequestLogAnalyzer::FileFormat::Rails3.create
```

So on inheritance:

```
class DummyInheritedFromRails3 < RequestLogAnalyzer::FileFormat::Rails3
end
```

DummyInheritedFromRails3.create Should call RequestLogAnalyzer::FileFormat::Base:

```
    def self.create(*args)
      # Ignore arguments
      return self.new(line_definer.line_definitions, report_definer.trackers)
    end
```

Here is where things go wrong:
1) line_definer.line_definitions = []
2) report_definer.trackers = []

**Comment by barttenbrinke** [comment]
Okay, the core problem is that class attributes are not inherited. Let me try to workaround this.

**Comment by barttenbrinke** [comment]
Could somebody please check the pull request and see if it works for them?

**Comment by wvanbergen** [comment]
Closing this, because the fix has been merged and released. Feel free to reopen if the problem persists.
