### ISSUE TITLE
Apache log "No trackers set up in Summarizer! (RuntimeError)"

### ISSUE THREAD

**Issue by baskinsy** [wvanbergen/request-log-analyzer#148]
I'm getting this when i try to run the analyzer against some apache logs.

./bin/request-log-analyzer --apache-format vhost_combined /var/log/apache2/other_vhosts_access.log 
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.12.9
Website: http://railsdoctors.com

/s5Home/stratos/request-log-analyzer/lib/request_log_analyzer/aggregator/summarizer.rb:57:in `prepare': No trackers set up in Summarizer! (RuntimeError)
        from /s5Home/stratos/request-log-analyzer/lib/request_log_analyzer/controller.rb:332:in`run!'
        from /s5Home/stratos/request-log-analyzer/lib/request_log_analyzer/controller.rb:332:in `each'
        from /s5Home/stratos/request-log-analyzer/lib/request_log_analyzer/controller.rb:332:in`run!'
        from ./bin/request-log-analyzer:129

My log format from apache2.conf is:

LogFormat "%a %l %v %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" **%T/%D**" vhost_combined

**Comment by barttenbrinke** [comment]
Could you paste a few lines of your apache log here?

**Comment by baskinsy** [comment]
Thanks for the answer. Here are some lines.

72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "GET /vtiger6/layouts/vlayout/modules/Vtiger/resources/Vtiger.js?&v=5.10.38 HTTP/1.1" 304 - "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/683**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "GET /vtiger6/modules/PrintTemplates/resources/TemplatePreview.js?&v=5.10.38 HTTP/1.1" 304 - "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/830**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "GET /vtiger6/layouts/vlayout/modules/Vtiger/resources/Detail.js?&v=5.10.38 HTTP/1.1" 304 - "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/406**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "GET /vtiger6/libraries/bootstrap/js/less.min.js HTTP/1.1" 304 - "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/472**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "POST /vtiger6/index.php HTTP/1.1" 200 20 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/68548**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:54 +0000] "POST /vtiger6/index.php HTTP/1.1" 200 50 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/101201**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:41:55 +0000] "GET /vtiger6/pageload.php?page_request=1382197312&page_ready=1382197332.658&page_load=1382197333.009&page_xfer=21.009&client_tzoffset=-18000&client_now=2013-10-19T15%3A42%3A13.010Z HTTP/1.1" 200 20 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=PrintTemplates&view=Detail&record=29" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/2025**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:42:02 +0000] "POST /vtiger6/index.php HTTP/1.1" 200 687 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=Invoice&view=Detail&record=8440" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/114537**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:42:02 +0000] "GET /vtiger6/modules/PrintTemplates/resources/Print.js?_=1382197340583 HTTP/1.1" 200 544 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=Invoice&view=Detail&record=8440" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/1439**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:42:04 +0000] "POST /vtiger6/index.php HTTP/1.1" 200 2359 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=Invoice&view=Detail&record=8440" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/895982**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:42:05 +0000] "GET /vtiger6/modules/PrintTemplates/resources/TemplatePreview.js?_=1382197343058 HTTP/1.1" 200 482 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=Invoice&view=Detail&record=8440" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/1489**
72.204.80.86 - psi-equipment.od1.vtiger.com [19/Oct/2013:15:42:05 +0000] "GET /vtiger6/modules/PrintTemplates/resources/Print.js?_=1382197343126 HTTP/1.1" 200 544 "https://psi-equipment.od1.vtiger.com/vtiger6/index.php?module=Invoice&view=Detail&record=8440" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/759**
99.111.110.47 - roundrockenterprises.od1.vtiger.com [19/Oct/2013:15:42:08 +0000] "POST /index.php HTTP/1.1" 200 942 "https://roundrockenterprises.od1.vtiger.com/index.php?action=index&module=MailManager" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **2/2357655**
99.111.110.47 - roundrockenterprises.od1.vtiger.com [19/Oct/2013:15:42:11 +0000] "POST /index.php HTTP/1.1" 200 1960 "https://roundrockenterprises.od1.vtiger.com/index.php?action=index&module=MailManager" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36" **0/657610**

**Comment by barttenbrinke** [comment]
What does
./bin/request-log-analyzer --format apache --apache-format combined /var/log/apache2/other_vhosts_access.log
give you?

**Comment by baskinsy** [comment]
The above command with "combined" runs ok but produces zero results. With "vhost_combined" it throws the same error.

**Comment by barttenbrinke** [comment]
Please update to v1.12.10 and try:
./bin/request-log-analyzer --format apache --apache-format vhost_combined /var/log/apache2/other_vhosts_access.log

**Comment by baskinsy** [comment]
We have progress! It runs ok, without the error, but with no results also.

Processsed File:     /var/log/apache2/other_vhosts_access.log
Parsed lines:        0  
Skipped lines:       0  
Parsed requests:     0  
Skipped requests:    0                                       

There were no requests analyzed.

**Comment by barttenbrinke** [comment]
It parses the lines you pasted fine for me... are they different?

**Comment by baskinsy** [comment]
I cannot find any difference...

It works if I copy-paste the above lines (those i gave you) to a new file, but not when trying directly on the log file.

**Comment by baskinsy** [comment]
We found the difference. The editor here made the "*" to become bold characters. All numbers at the end of each line are not bold but have "*" in front and at the end.

**Comment by baskinsy** [comment]
This is a correct line.

```
117.195.61.202 - inspyretechnologies.od1.vtiger.com [21/Oct/2013:10:28:51 +0000] "GET /vtiger6/pageload.php?page_request=1382351324&page_ready=1382351330.871&page_load=1382351332.847&page_xfer=8.847&client_tzoffset=19800&client_now=2013-10-21T10%3A28%3A52.847Z HTTP/1.1" 200 20 "https://inspyretechnologies.od1.vtiger.com/vtiger6/index.php?module=Leads&view=List" "Mozilla/5.0 (Windows NT 5.1; rv:13.0) Gecko/20100101 Firefox/13.0.1" *0/969*
```

**Comment by barttenbrinke** [comment]
Ok, as far as I can see, this is a custom logformat, which is fine, but you have to tell request-log-analyzer the format, as it isn't shipped with this. For example this will match most of your data:

```
./bin/request-log-analyzer --format apache --apache-format '%h %l %v %t "%r" %>s %b "%{Referer}i" "%{User-agent}i"' /var/log/apache2/other_vhosts_access.log
```

If I am wrong, please tell me, so we can add this format as the vhost_combined format.

**Comment by baskinsy** [comment]
The last command worked and it produces results, although I cannot see  request duration time results.

My log format definition on apache2.conf is:

```
LogFormat "%a %l %v %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" **%T/%D**" vhost_combined
```

So I used that command:

```
./bin/request-log-analyzer --format apache --apache-format '%h %l %v %t "%r" %>s %b "%{Referer}i" "%{User-agent}i" **%T/%D**' /var/log/apache2/other_vhosts_access.log
```

Can you verify it is ok?

I want to thank you for your effort to make this very good analyzer to work with my peculiar format. I'm forced to use this format because our partner has its own analysis software.

Thank you again!

**Comment by barttenbrinke** [comment]
Because you are passing both %T and %D, rla is mapping them both to duration, which will make one overwrite the other, which is probably not what you want. Also you need to specify the unit of D.
This will work as a workaround, but it isn't very nice though.. let me think in how to make this nicer.

```
./bin/request-log-analyzer --format apache --apache-format '%h %l %v %t "%r" %>s %b "%{Referer}i" "%{User-agent}i" **%x/%{micro}D**'
```

%x is unmatched by rla, so everything in there is just dropped.

**Comment by barttenbrinke** [comment]
This looks right to me

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Request duration - by mean                                             ┃ Hits ┃    Sum ┃   Mean ┃ StdDev ┃    Min ┃    Max ┃    95 %tile
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
/index.php                                                             ┃    2 ┃  3.02s ┃  1.51s ┃  1.20s ┃  0.66s ┃  2.36s ┃ 0.65s-2.37s
/vtiger6/index.php                                                     ┃    4 ┃  1.18s ┃  0.30s ┃  0.40s ┃  0.07s ┃  0.90s ┃ 0.07s-0.90s
/vtiger6/pageload.php?page_request=1382197312&page_ready=1382197332.658┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/modules/PrintTemplates/resources/TemplatePreview.js?_=13821973┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/modules/PrintTemplates/resources/Print.js?_=1382197340583     ┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/modules/PrintTemplates/resources/TemplatePreview.js?&v=5.10.38┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/modules/PrintTemplates/resources/Print.js?_=1382197343126     ┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/layouts/vlayout/modules/Vtiger/resources/Vtiger.js?&v=5.10.38 ┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/libraries/bootstrap/js/less.min.js                            ┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
/vtiger6/layouts/vlayout/modules/Vtiger/resources/Detail.js?&v=5.10.38 ┃    1 ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃  0.00s ┃ 0.00s-0.00s
```

**Comment by wvanbergen** [comment]
Is still still an active issue? Feel free to reopen if this is not yet resolved.
