### ISSUE TITLE
rails-format option results in teaser_check_failed

### ISSUE THREAD

**Issue by juriglx** [wvanbergen/request-log-analyzer#149]
if i run `request-log-analyzer production.log` i get a nice output for my logfile. 

But if i run `request-log-analyzer production.log --rails-format minimal` the output is `Warnings:            teaser_check_failed: 1297`. And it doesn't matter, which rails-format i use, even production, which is the default format according to the documentation, results only in a number of teaser_check_failed warnings.

If i add --debug, the error is:
`WARNING :teaser_check_failed on line 184: Teaser matched for :processing, but full line did not:`

Am I missing something?

**Comment by juriglx** [comment]
After reading some of the code, rails-format seems only only to be supported for the rails (rails 2) format, not for rails3. This should be added to the documentation.

**Comment by wvanbergen** [comment]
Updated the wiki accordingly.
