### ISSUE TITLE
Munin extention

### ISSUE THREAD

**Issue by barttenbrinke** [wvanbergen/request-log-analyzer#15]
As request log analyzer can very easily be used to find any errors that occured in say the last five munites, whould a munin extention be a good addition?

**Comment by wvanbergen** [comment]
Maybe such an extension can be created as a separate project?

**Comment by barttenbrinke** [comment]
Extension is now available in /lib/rla_tracker :)

**Comment by barttenbrinke** [comment]
Also a wiki page is now available.
Should I move it to a new project called munin-rails-plugins ?

**Comment by wvanbergen** [comment]
I am for a separate project. The file in question is buried somewhere in the tree, is is not part of the application itself, so nobody will find this kind of functionality.

Moreover, you may want to add some (rake) scripts to ease the installation, which would be out of place in the current r-l-a repo.

**Comment by barttenbrinke** [comment]
True. However, r-l-a is great for this. I have really cool munin graphs :)
As there allready is a rails-munin app, how should I call it? munin-rails-plugins?

**Comment by barttenbrinke** [comment]
See https://github.com/barttenbrinke/munin-plugins-rails/tree
