### ISSUE TITLE
Error installing request-log-analyzer

### ISSUE THREAD

**Issue by ocaloke** [wvanbergen/request-log-analyzer#150]
Getting an undefined method `map'  error when installing the request-log-analyzer gem (on Mac OSX 10.6.8). 

MacBook-Pro-5$ sudo gem install request-log-analyzer
Password:
Successfully installed request-log-analyzer-1.12.10
1 gem installed
Installing ri documentation for request-log-analyzer-1.12.10...
ERROR:  While executing gem ... (NoMethodError)
    undefined method `map' for Gem::Specification:Class
MacBook-Pro-5$

**Comment by wvanbergen** [comment]
Does it work if you run the following command?

sudo gem install request-log-analyzer --no-rdoc --no-ri

**Comment by ocaloke** [comment]
Yes, that worked fine. Did it install the gem but not the docs?

**Comment by wvanbergen** [comment]
Yes, it left out the docs this way.
The root cause is that your version of ruby gems is outdated. I think you can update it using sudo gem update--system
