### ISSUE TITLE
 Could not find request-log-analyzer (>= 0)

### ISSUE THREAD

**Issue by alfredpl** [wvanbergen/request-log-analyzer#151]
sysadmin@system6:~/dev/arrivuapps$ request-log-analyzer log/development.log 
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find request-log-analyzer (>= 0) amongst [0xffffff-0.1.0, Ascii85-1.0.2, actionmailer-3.2.12, actionpack-3.2.12, active_merchant_ccavenue-0.1.0, active_utils-2.0.1, active_utils-1.0.5, activemerchant-1.32.1, activemodel-3.2.12, activerecord-3.2.12, activeresource-3.2.12, activesupport-3.2.12, acts_as_commentable-3.0.1, addressable-2.3.5, afm-0.2.0, ancestry-2.0.0, annotate-2.4.1.beta1, arel-3.0.2, bcrypt-ruby-3.1.2, bcrypt-ruby-3.1.0, best_in_place-2.1.0, better_errors-0.8.0, binding_of_caller-0.7.1, bootstrap-sass-2.3.2.2, bootstrap-sass-2.3.1.0, bootstrap-tooltip-rails-0.1, bootstrap-will_paginate-0.0.6, breadcrumbs_on_rails-2.3.0, builder-3.0.4, bundler-1.3.5, bundler-unload-1.0.1, cancan-1.6.9, capybara-2.1.0, chunky_png-1.2.9, client_side_validations-3.2.6, client_side_validations-simple_form-2.1.0, climate_control-0.0.3, cocaine-0.5.2, coderay-1.1.0, coderay-1.0.9, coffee-rails-3.2.2, coffee-script-2.2.0, coffee-script-source-1.6.3, daemons-1.1.9, database_cleaner-0.9.1, debug_inspector-0.0.2, debugger-ruby_core_source-1.2.3, delayed_job-4.0.0, delayed_job-3.0.5, delayed_job_active_record-4.0.0, delayed_job_active_record-0.4.4, delayed_job_web-1.2.0, devise-2.2.3, diff-lcs-1.2.4, email_spec-1.4.0, erubis-2.7.0, execjs-2.0.2, execjs-1.4.0, factory_girl-4.2.0, factory_girl_rails-4.2.1, faker-1.0.1, faraday-0.8.8, faraday-0.8.7, figaro-0.6.4, flickraw-0.9.6, flickraw-cached-20120701, haml-4.0.3, hashery-2.1.1, hashery-2.1.0, hashie-2.0.5, hike-1.2.3, httpauth-0.2.0, hub-1.10.6, i18n-0.6.5, i18n-0.6.4, journey-1.0.4, jquery-minicolors-rails-0.0.3, jquery-rails-2.2.1, json-1.7.7, jwt-0.1.8, launchy-2.3.0, letsrate-1.0.8, libv8-3.11.8.17-x86_64-linux, mail-2.4.4, mime-types-1.25, mime-types-1.23, mini_portile-0.5.1, mini_portile-0.5.0, multi_json-1.8.1, multi_json-1.7.7, multipart-post-1.2.0, nokogiri-1.6.0, oauth-0.4.7, oauth2-0.8.1, omniauth-1.1.4, omniauth-facebook-1.4.1, omniauth-google-oauth2-0.1.17, omniauth-linkedin-0.1.0, omniauth-oauth-1.0.1, omniauth-oauth2-1.1.1, orm_adapter-0.4.0, paperclip-3.5.1, payday-1.1.0, pdf-reader-1.3.3, pg-0.15.0, polyglot-0.3.3, prawn-0.12.0, prawn-svg-0.9.1.11, quiet_assets-1.0.2, rack-1.4.5, rack-cache-1.2, rack-protection-1.5.0, rack-ssl-1.3.3, rack-test-0.6.2, rails-3.2.12, rails_config-0.3.3, railties-3.2.12, rake-10.1.0, rdoc-3.12.2, ref-1.0.5, rest-client-1.6.7, rolify-3.2.0, rspec-core-2.13.1, rspec-expectations-2.13.0, rspec-mocks-2.13.1, rspec-rails-2.13.1, ruby-debug-base19x-0.11.30.pre12, ruby-debug-ide-0.4.17.beta17, ruby-rc4-0.1.5, rubygems-bundler-1.2.2, rvm-1.11.3.8, sass-3.2.12, sass-3.2.9, sass-rails-3.2.6, simple_form-2.1.0, sinatra-1.4.3, sprockets-2.2.2, sqlite3-1.3.7, themes_for_rails-0.5.1, therubyracer-0.11.4, thor-0.18.1, tilt-1.4.1, tinymce-rails-4.0.2, treetop-1.4.15, treetop-1.4.14, ttfunk-1.0.3, tzinfo-0.3.38, tzinfo-0.3.37, uglifier-2.0.1, warden-1.2.3, warden-1.2.1, wicked_pdf-0.9.6, will_paginate-3.0.4, xpath-2.0.0] (Gem::LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /usr/local/bin/request-log-analyzer:22:in`<main>'

**Comment by wvanbergen** [comment]
Seems like request-log-anayzer isn't installed in your ruby environment.
Run (sudo) gem install request-log-analyzer.
