### ISSUE TITLE
Drop Query String from URLs?

### ISSUE THREAD

**Issue by miketheman** [wvanbergen/request-log-analyzer#152]
Pardon me if this feature already exists, but since many URLs may provide a query string that uniquely identifies that request (cookie, timestamp, etc), trying to parse out the data is made more difficult.

Is there a flag somewhere in teh code for nginx/apache/haproxy formatters that would drop the query string during parsing?

Is that something you'd be open to adding?

**Comment by wvanbergen** [comment]
A feature like that doesn't exists currently. I certainly would welcome an addition to make it possible though.
