### ISSUE TITLE
Support fake basic auth %u field

### ISSUE THREAD

**Issue by gilesw** [wvanbergen/request-log-analyzer#157]
SSLOptions +FakeBasicAuth

in apache can be used to write out the connecting client's certificate to the %u field, this isn't allowed in the %u regex.

Example:-

/C=UK/ST=XXX/L=XXXX/O=XXXX/CN=common-name_with-dashes_and_underscores

**Comment by wvanbergen** [comment]
Can you paste a line of your log, and your format string?

**Comment by gilesw** [comment]
Sure but I'll need to change the values as in the example given above. Here's the format line:-

%h %l %u %t "%r" %s %b %T "%{Referer}i" "%{User-agent}i"
and an example line
x.x.x.x - /C=UK/ST=XXXX/L=XXXX/O=XXXX/CN=XXX-XXX-xxxx [01/Mar/2014:00:00:02 +0000] "GET /REST/something HTTP/1.1" 404 140 0 "-" "-"

**Comment by wvanbergen** [comment]
Hey, I think I finally wrote a fix for that. Any chance you can give #172 a swing?

**Comment by gilesw** [comment]
Hopefully this doesn't re-open the ticket but I can confirm that the version with that merge in does handle these logs.

**Comment by barttenbrinke** [comment]
👍
