### ISSUE TITLE
Small correction to HTML output

### ISSUE THREAD

**Issue by jefflunt** [wvanbergen/request-log-analyzer#159]
Would anyone be opposed to a patch to correct a small issue in the HTML output?
- Change [this](https://github.com/wvanbergen/request-log-analyzer/blob/89f984075d0942c5337e4537cca8d9fdb646312b/lib/request_log_analyzer/output/html.rb#L105) into a class rather than an id since it's used on multiple elements, and rename it to something like `rla-report-table`
- Change [this line](https://github.com/wvanbergen/request-log-analyzer/blob/89f984075d0942c5337e4537cca8d9fdb646312b/lib/request_log_analyzer/output/html.rb#L56) into this:

``` ruby
  @io << tag(:table, {:class => 'rla-report-table', :cellspacing => 0}) do |content|
```

**Comment by wvanbergen** [comment]
Merged your PR, closing
