### ISSUE TITLE
Error creating a database file.

### ISSUE THREAD

**Issue by alexdean** [wvanbergen/request-log-analyzer#17]
I can parse a log file successfully, but when I attempt to save the results into a sqlite file, I get the error described below.  Does this file need to already exist?  Help text says the RLA will create it for me, so I have not created the database file before running the command below.

$ rails --version
Rails 2.2.2
$ ruby --version
ruby 1.8.7 (2008-08-11 patchlevel 72) [i686-darwin9.6.0]

$ request-log-analyzer --database web2.db log/ipsm_dev_oracle.log
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.2.1
Website: http://railsdoctors.com

/opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:326:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/connection_specification.rb:121:in`retrieve_connection'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/abstract/connection_specification.rb:113:in `connection'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/migration.rb:346:in`method_missing'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/migration.rb:326:in `say_with_time'
    from /opt/software/wxweb/opt/lib/ruby/1.8/benchmark.rb:293:in`measure'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/migration.rb:326:in `say_with_time'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/migration.rb:342:in`method_missing'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/aggregator/database.rb:141:in `create_request_table_and_class'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/aggregator/database.rb:166:in`create_database_schema!'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/aggregator/database.rb:27:in `prepare'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/controller.rb:193:in`run!'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/controller.rb:193:in `each'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/../lib/request_log_analyzer/controller.rb:193:in`run!'
    from /opt/software/wxweb/opt/lib/ruby/gems/1.8/gems/wvanbergen-request-log-analyzer-1.2.3/bin/request-log-analyzer:93
    from /opt/software/wxweb/opt/bin/request-log-analyzer:19:in `load'
    from /opt/software/wxweb/opt/bin/request-log-analyzer:19

**Comment by wvanbergen** [comment]
The exact same syntax works for me. What version of the sqlite3-ruby gem do you have installed? Use "gem list sqlite" to see what versions are available. I am using sqlite3-ruby version 1.2.4.

**Comment by alexdean** [comment]
I installed the newly-released request-log-analyzer-1.2.4, and no longer encounter this error.  Thanks!

**Comment by wvanbergen** [comment]
This was fixed by more robust handling of connections for the table migrations.
