### ISSUE TITLE
unable to parse oink files

### ISSUE THREAD

**Issue by timuckun** [wvanbergen/request-log-analyzer#171]
It can't seem to parse oink logs. Standalone or inside the of the rails log

Parsable lines were encountered without a header line before it. It
could be that logging is not setup correctly for your application.
Visit this website for logging configuration tips:
http://github.com/wvanbergen/request-log-analyzer/wikis/configure-logging

I have used both 

Rails.application.middleware.use( Oink::Middleware, :logger=> Hodel3000CompliantLogger.new( File.join(Rails.root, 'log', 'oink.log') ))

and using the standard rails log  I have also tried using the hodel logger with rails.

**Comment by wvanbergen** [comment]
I think the Oink log parser only works in combination with Rails 2 logs. So if you are using a newer Rails version it's likely not going to work.
