### ISSUE TITLE
SyntaxError isn't caught when parsing parameter hashes (via eval)

### ISSUE THREAD

**Issue by searlm** [wvanbergen/request-log-analyzer#175]
If a parameter hash is truncated in a rails log, or is otherwise malformed, the resulting SyntaxError doesn't get caught by convert_eval, and request-log-analyzer crashes.

Example log entry:

```
2014-09-08T23:37:03+00:00 blah blah[foo]: [ID blah user.info] Parameters: {"foo"=>{"bar"=>"baz
```

I'm not sure what other exceptions are possible/expected here, so I just rescued Exception, as seen in the diff below. 

```
diff --git a/lib/request_log_analyzer/request.rb b/lib/request_log_analyzer/request.rb
index 06bf46b..9cb6a81 100644
--- a/lib/request_log_analyzer/request.rb
+++ b/lib/request_log_analyzer/request.rb
@@ -58,7 +58,7 @@ module RequestLogAnalyzer
       # Converts :eval field, which should evaluate to a hash.
       def convert_eval(value, _capture_definition)
         eval(sanitize_parameters(value)).reduce({}) { |h, (k, v)| h[k.to_sym] = v; h }
-      rescue
+      rescue Exception
         nil
       end
```

**Comment by wvanbergen** [comment]
I don't really like this solution. This will also catch OutOfMemory exceptions, Interrupt exceptions, and a whole bunch of stuff that we shouldn't catch.
- The right solution is no not use eval: https://github.com/wvanbergen/request-log-analyzer/issues/169
- A stopgap measure could be catching StandardError, and SyntaxError.
