### ISSUE TITLE
Changing mail sender

### ISSUE THREAD

**Issue by yottanami** [wvanbergen/request-log-analyzer#187]
Is anyway to change the mail sender?
Because of this error:

```
smtp.rb:951:in `check_response': 451 4.1.8 Domain of sender address contact@railsdoctors.com does not resolve (Net::SMTPServerBusy)
```

**Comment by wvanbergen** [comment]
cc @barttenbrinke

**Comment by barttenbrinke** [comment]
You can use the mailfrom and mailfromname commandline options to do that.

**Comment by yottanami** [comment]
It can be useful

https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
