### ISSUE TITLE
Allow skipping first n bytes of file

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#19]
Add --skip-bytes <n> option to skip the first n bytes of a file. This makes it easier to not parse duplicate data.

**Comment by barttenbrinke** [comment]
Wouldn't a skip-lines option be more logical?

**Comment by wvanbergen** [comment]
Maybe that would be a nice feature as well, but bytes is useful to implement resuming, as you can simply store the filename, mtime and filesize of every logfile (which is what the database inserter already does). By skipping these bytes if the file has become bigger since the last parse, you can resume parsing a log that has new information in it.
