### ISSUE TITLE
Add specs for FileFormat subclassing

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#2]

**Comment by barttenbrinke** [comment]
What do you want to have speced? That they actually parse these filetypes?

**Comment by wvanbergen** [comment]
For example, you can do this:

```
class MyFileFormat < RequestLogAnalyzer::FileFormat::Rails

  # Add some additional lines here besides the standard Rails lines
  # Also, add some trackers to the report.

  # Hack the request class
  class Request < RequestLogAnalyzer::FileFormat::Rails::Request
    # hack the request class here
  end
end
```

See http://wiki.github.com/wvanbergen/request-log-analyzer/creating-your-own-file-format-definition for more information. This should behave as expected and currently is completely unspeced. We use this at Floorplanner to parse some of the custom lines we add to our log, like the current user and his account type.

**Comment by barttenbrinke** [comment]
So what do you want to spec? The hacks?

**Comment by wvanbergen** [comment]
- When subclassing a file format, all line types of the parent file format should be parsed, and the newly added line types should be parsed as well.
- The parent file format should be left unchanged (so it should not parse any of the added line types).

The last bullet seems very logical/simple, but I really struggled to get this working correctly when I was implementing fileformat subclassing.

The same points can be made for the report trackers.

**Comment by roele** [comment]
Had some problems implementing a FileFormat as described since line.header and line.footer are required which is not documented (raises invalid file format exception). For me is also unclear how to work with timestamp or categories etc. since i am a Ruby-Newbie.

**Comment by barttenbrinke** [comment]
Hello Roele :) I think the first question is: what are you trying to implement and what have you got so far?
