### ISSUE TITLE
Load version from gemspec file

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#20]
We always forget to update the version constant. The version in the .gemspec file is always correct, so we could use the value specified there.

**Comment by barttenbrinke** [comment]
With we, you mean you :)?

**Comment by wvanbergen** [comment]
I always use the royal plural. ;)

**Comment by barttenbrinke** [comment]
Excuse me your highness :P

**Comment by wvanbergen** [comment]
OK, we have now fixed this high-priority issue on master!

**Comment by barttenbrinke** [comment]
Nice work :)
