### ISSUE TITLE
Have --after use more intelligence than it does now

### ISSUE THREAD

**Issue by barttenbrinke** [wvanbergen/request-log-analyzer#21]
Like parsing from back to front to determine starting position if after was given and file bigger than x bytes.

**Comment by barttenbrinke** [comment]
```
def read_backwards_to_timestamp(path, timestamp)
  start = nil
  Elif.open(path) do |elif|
    elif.each do |line|
      if line =~ /\AProcessing .+ at (\d+-\d+-\d+ \d+:\d+:\d+)\)/
        time_of_request = Time.parse($1)
        if time_of_request < timestamp
          break
        else
          start = elif.pos
        end
      end
    end
  end

  file = open(path)
  file.seek(start) if start
  file
end
```

**Comment by wvanbergen** [comment]
Maybe a binary search through the file is even faster :-)
However, the above implementation is very Rails specific. I don't know if this can be implemented in a file formated agnostic way.

**Comment by barttenbrinke** [comment]
We could try to parse every line into a date :) Or have each file definition define a date_finder teaser regexp?
