### ISSUE TITLE
Provide better API interface for RLA

### ISSUE THREAD

**Issue by barttenbrinke** [wvanbergen/request-log-analyzer#22]
One other minor issue I've had with RLA is wishing there was an API that more closely mirrored the command-line invocation.  For example, I wish I could use it like a library sort of like:

```
result = StringIO.new
RequestLogAnalyzer.analyze( log, :after  => start_time,
                              :output => "HTML",
                              :file   => result )
```

**Comment by wvanbergen** [comment]
This would be nice as well for reading a configuration from a config file (see issue #16)

This may require rewriting the command line option parsing and handling. In that case, we may switch to optparse, the standard ruby library for this.

**Comment by barttenbrinke** [comment]
Command line now uses Base API.

```
# TODO:
#   Check if defaults work (Aggregator defaults seem wrong).
#   Refactor :database => options[:database], :dump => options[:dump] away from contoller intialization.
```

**Comment by barttenbrinke** [comment]
Good enough for now
