### ISSUE TITLE
--report-amount command line switch

### ISSUE THREAD

**Issue by bananastalktome** [wvanbergen/request-log-analyzer#25]
It would be nice to have an --amount command line switch to toggle the number of hits returned in the output, be it HTML, plain text, or yaml, with the ability to specify a particular number or unlimited.

**Comment by wvanbergen** [comment]
The switch is probably going to be called `--report-amount`.

**Comment by wvanbergen** [comment]
I will also add a command line option `--report-sort mean,sum,stddev` to specify what tables should be included in the report and how these tables should be sorted.
- `--report-sort mean,stddev,sum`: Sort results by mean, sum and standard deviation. This will display 3 different tables.
- `--report-amount 20`: Only show the top 20 results for every sorting/table.
- `--report-amount all`: Show all the results for every sorting/table.

**Comment by wvanbergen** [comment]
These command line switches are now available in HEAD and will show up in the next release.
