### ISSUE TITLE
don't work since I updated version

### ISSUE THREAD

**Issue by grimen** [wvanbergen/request-log-analyzer#33]
I run (in my project):

request-log-analyzer log/development.log 

Outputs nothing of value, but I see warning:

...
Warnings:            teaser_check_failed: 312, no_current_request: 302
...

It worked for me before I updated the gem yesterday.

**Comment by wvanbergen** [comment]
Hmmm, it seems to be working fine for me. Can you maybe send (the first part of) your log file to me? You can send it to willem@railsdoctors.com

**Comment by grimen** [comment]
It worked after I cleared the logs. Too late! ;) I'll do that if I get the same error again. Thanks.

**Comment by wvanbergen** [comment]
OK, maybe there was some strange cruft left in the old log files that r-l-a couldn't handle. Happy to hear it works for you again!
