### ISSUE TITLE
Add integration spec for mailer

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#34]
To ensure that everything works to mail reports, including the `--mail` command line option.

**Comment by barttenbrinke** [comment]
How can you test that easily? Spawn a mail server with something like pony and then wrap around?

**Comment by wvanbergen** [comment]
IMHO, the most important thing to test is that the `--mail` command line argument actually invokes the mailer component. The actual SMTP stuff is less important. Maybe we can check if the appropriate Net::SMTP method is called?

**Comment by barttenbrinke** [comment]
Can we set up some oneliner SMTP server in ruby to catch the email?

**Comment by barttenbrinke** [comment]
How does rails test actionmailer?

**Comment by barttenbrinke** [comment]
This looks interesting: http://snippets.dzone.com/posts/show/3932

**Comment by barttenbrinke** [comment]
Apparently Mailtrap is designed specifically for this: http://matt.blogs.it/entries/00002655.html http://rubymatt.rubyforge.org/mailtrap/

**Comment by barttenbrinke** [comment]
Wow. that should be damn simple:
Remove mailtrap log
mailtrap start
request-log-analyzer start
mailtrap stop
Check if mail was received in mailtrap log

But it will add a requirement to the test suite.. Which should be pretty ok I Guess

**Comment by barttenbrinke** [comment]
afd95ca..5b2d042 via mailtrap
