### ISSUE TITLE
output html for report with rack format throw exception undefined method `colorize'

### ISSUE THREAD

**Issue by jessy** [wvanbergen/request-log-analyzer#40]
when I use this set of options on a rack formatted log file :
request-log-analyzer --format rack log_file.log --output html

the html report is printed but a exception is finally thrown :

/Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/tracker/traffic.rb:92:in `report': undefined method`colorize' for #RequestLogAnalyzer::Output::HTML:0x531178 (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/aggregator/summarizer.rb:128:in `report'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/aggregator/summarizer.rb:128:in`each'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/aggregator/summarizer.rb:128:in `report'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/controller.rb:327:in`run!'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/controller.rb:327:in `each'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/../lib/request_log_analyzer/controller.rb:327:in`run!'
    from /Library/Ruby/Gems/1.8/gems/request-log-analyzer-1.5.0/bin/request-log-analyzer:116
    from /usr/bin/request-log-analyzer:19:in `load'
    from /usr/bin/request-log-analyzer:19

**Comment by wvanbergen** [comment]
I fixed this issue. Please install version 1.5.1.
