### ISSUE TITLE
Crash - line definition bug

### ISSUE THREAD

**Issue by ngmoco** [wvanbergen/request-log-analyzer#43]
I'm running an analysis of a syslog file and I get this crash.

/var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/line_definition.rb:57:in `=~': broken UTF-8 string (ArgumentError)                                                                                                                           ] ETA:  25:56:27
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/line_definition.rb:57:in`matches'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/file_format.rb:268:in `block in parse_line'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/file_format.rb:267:in`each'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/file_format.rb:267:in `parse_line'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:163:in`parse_line'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:151:in `parse_io'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:112:in`block in parse_file'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:112:in `open'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:112:in`parse_file'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/source/log_parser.rb:62:in `each_request'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/lib/request_log_analyzer/controller.rb:320:in`run!'
        from /var/lib/gems/1.9.0/gems/request-log-analyzer-1.6.1/bin/request-log-analyzer:120:in `<top (required)>'
        from /var/lib/gems/1.9.0/bin/request-log-analyzer:19:in`load'
        from /var/lib/gems/1.9.0/bin/request-log-analyzer:19:in `<main>'

**Comment by wvanbergen** [comment]
This probably is hard to debug without the line in the log file causing this. Are you able to pinpoint the line in your log files that triggers this exception?

Moreover, I see that you are using Ruby 1.9. Can you test the same file under Ruby 1.8, and see if the same exception occurs?

**Comment by ngmoco** [comment]
I am currently testing it with 1.8 and will let you know how it goes, although I'm pretty certain it's a 1.9 bug. It's going to take a day to run.

I don't know what line caused this error. I will _try_ to find it and if I do I'll put it in the comments.

**Comment by ngmoco** [comment]
Works fine with 1.8. This is a confirmed 1.9 bug.

**Comment by wvanbergen** [comment]
Are you by any chance writing binary data to your log? This may cause the troubles you are experiencing.

Anyway, I think I may be able to solve this issue by always reading files with a forced binary/ascii encoding. Let me see if a can cook up a quick fix.

**Comment by wvanbergen** [comment]
I have released 1.6.2 with a patch that (hopefully) fixes this issue by reading files as binary data streams, and rescuing the exception you are experiencing.

Note that r-l-a runs faster on Ruby 1.8 than on 1.9, because of this string encoding / transcoding performance hit.
