### ISSUE TITLE
import data to existing database

### ISSUE THREAD

**Issue by matzke** [wvanbergen/request-log-analyzer#44]
how do i import data to an existing database?

i get an error saying that the index of table XY already exists ... guessing that r-l-a is trying to create the database schema again!?

thanks for support & keep up the good work!

**Comment by wvanbergen** [comment]
What version are you using? I believe I resolved this issue in version 1.6.2

**Comment by matzke** [comment]
hey Willem,
thank you for the quick reply and sorry for trouble. I was using 1.5.1 and with 1.6.2 everythink just works fine!

**Comment by wvanbergen** [comment]
No problem! Glad you like using r-l-a.
