### ISSUE TITLE
Delayed Job format doesn't support incremental analysis

### ISSUE THREAD

**Issue by itsderek23** [wvanbergen/request-log-analyzer#45]
When I pass the "--after" option to RLA v1.6.2 for a Delayed Job file, the following exception is returned:

/usr/lib/ruby/gems/1.8/gems/request-log-analyzer-1.6.2/bin/../lib/request_log_analyzer/filter/timespan.rb:35:in `<=': comparison of Fixnum with nil failed (ArgumentError)

Full trace: http://gist.github.com/292222

I believe this may be because the Delayed Job log does not have timestamps (at least v 1.7.0, the most recent version). 

Sample:
- [JOB] aquiring lock on MassUpdate#copy_from_file
- [JOB] MassUpdate#copy_from_file completed after 1.1547

If this is the case, I don't think there is anything RLA can do. If so, let me know and I'll add info the Delayed Job format wiki entry.

**Comment by wvanbergen** [comment]
You're right, I checked and the file format does not contain timestamps, so the @--before@ and @--after@ options cannot be used. If you could make a mention of this in the wiki, that would be great.

I will open an issue on Delayed::Job to include timestamps in their logs, so hopefully this will be resolved in the future.

**Comment by itsderek23** [comment]
I've added a note on the DelayedJob page for the RLA wiki. 

Thanks!

**Comment by wvanbergen** [comment]
Great work! I submitted a patch to delayed job to include timestamps in their logs, and it will be included in the next version. Then, we can parse in in r-l-a as well, enabling the time based features.
