### ISSUE TITLE
--silent option

### ISSUE THREAD

**Issue by charl** [wvanbergen/request-log-analyzer#46]
A --silent option that skips printing the marketing blurb and output feedback would be great for when you need to run this from cron.

I realize that you could simply ignore STDOUT/STDERROR with redirection but I'd rather the script not print anything so that one is able to catch real errors that may arise from running it from cron.

**Comment by barttenbrinke** [comment]
If you want to hook it in to some automated error reporting, it makes more sense to look at the --yaml option, just like the munin plugins do: http://barttenbrinke.github.com/munin-plugins-rails/

This will skip the marketing blurb for you and provide a machine parsable format.

**Comment by wvanbergen** [comment]
If you want to add a `--silent` option, please fork the project, cook up a patch and send us a pull request. We will gladly merge such as feature!

**Comment by barttenbrinke** [comment]
Implemented in current master
   f9a9d5e..90153c0  master -> master
