### ISSUE TITLE
High memory usage when parsing large lines

### ISSUE THREAD

**Issue by itsderek23** [wvanbergen/request-log-analyzer#47]
I've noticed a large increase in memory usage when parsing large line entries in a log file. It does not appear to be a fault of RLA but an issue with IO#gets. 

It appears that as the line is read in chunks and written to a buffer, memory usage grows. I've seen cases of greater than 500 MB memory usage when parsing a log file with 5 MB line entries. 

While it isn't good practice for a log file to contain these large lines, we've seen it several times in Rails apps that handle file uploads. The biggest issue is when RLA is run in the background - it could exhaust the memory usage on a server without the user being aware that the process is running. 

To reproduce:

Create a log file with a 5 MB line entry:

ruby -e 'puts "one"; puts "t" \* 1024 \* 1024 \* 5' > big_data.txt

Run RLA and observe the memory usage:

request-log-analyzer big_data.txt

I've observed this on Ruby 1.8.6 (haven't tested on other releases).

I'm looking at a possible fix: When reading the contents of a file, ignore chunks that don't have a line separator. If RLA reads the file in 1024 segments, it can be reasonably sure that the request path will not be this long. 

Just wanted to make sure you are aware. I'll submit a pull request when I have something to demo.

**Comment by wvanbergen** [comment]
Hmmm, one would hope that people learn how to use filter_parameter_logging correctly ;)

I wonder though in what cases lines get so huge. An upload usually just appears as ":upload => StringIO:456456" in my logs.

In any case, a fix for this issue would be great. However, make sure that the extra processing/checks don't slow RLA down too much.

**Comment by barttenbrinke** [comment]
The simplest thing I can think of is to just drop a line if the length is longer than X characters.

**Comment by itsderek23** [comment]
HI Bartteen,

I think the problem is that File#gets cannot easily tell the length of a line. It appears to read from the file until it encounters a line separator. For large lines, it buffers the contents which uses a lot of memory. 

Here's a workaround we are using. It reads the file in 100 KB chunks and if the chunk does not contain the line separator, it is thrown out (instead of adding to the buffer). It's  unlikely a 100 KB chunk would not contain a line separator. If it doesn't, something weird is happening. 

I'm not sure this belongs in RLA. It might just be best to close the ticket with the documented work around we are using.

http://gist.github.com/381444

**Comment by barttenbrinke** [comment]
Thanks for the mixin. Should we add this to the wiki?

**Comment by barttenbrinke** [comment]
Or we could just call the mixin in RLA. As this can cause memory problems on a server environment, which isn't cool. --advanced-mem-protection :)?

**Comment by wvanbergen** [comment]
A command line options sounds like a good idea. Any idea how much this slows RLA down in normal operation?

**Comment by barttenbrinke** [comment]
Head now has the --gets-memory-protection option. It is about 10% slower. The option is not documented yet.

**Comment by wvanbergen** [comment]
Just like 90% of the command line options, so nothing new here :-)

**Comment by loopj** [comment]
The current "require" line for this fix isn't reliable.

I recommend changing it to something like:
require File.dirname(**FILE**) + '/../mixins/gets_memory_protection' if arguments[:gets_memory_protection]

(or a cleaner version, as long as its more absolute)

**Comment by barttenbrinke** [comment]
In master

**Comment by barttenbrinke** [comment]
And thanks for the update :)
