### ISSUE TITLE
line_definition :print 

### ISSUE THREAD

**Issue by matzke** [wvanbergen/request-log-analyzer#48]
minor finding:

line_definition :print  do |line| does not work ... maybe names can be escaped?

(using rla 1.6.2)

**Comment by wvanbergen** [comment]
As far as I can see, there is no reason why this shouldn't work. What kind of error message do you get? And does your line definition work with another name?

**Comment by wvanbergen** [comment]
Wait, you're right. Because I was using method_missing, line definitions that used a name that is also a method of Object or Kernel could not be used. This is now fixed and released as version 1.6.4.

**Comment by matzke** [comment]
thank u!!
