### ISSUE TITLE
Add MariaDB log support

### ISSUE THREAD

**Issue by barttenbrinke** [wvanbergen/request-log-analyzer#50]
http://askmonty.org/wiki/MariaDB

**Comment by wvanbergen** [comment]
Is there any difference in logging between MariaDB and MySQL?

**Comment by barttenbrinke** [comment]
http://askmonty.org/wiki/Manual:Slow_Query_Log_Extended_Statistics

**Comment by wvanbergen** [comment]
Please provide a log snippet so that we can implement the file format.
