### ISSUE TITLE
Include hostname in report

### ISSUE THREAD

**Issue by anthias** [wvanbergen/request-log-analyzer#51]
We're mailing reports using cron.daily from our cluster. It would be nice if the report showed which host the report came from.
Thanks!
                      jeff

**Comment by barttenbrinke** [comment]
Would it be a good idea if you could pass something like --note, which will get placed at the bottom of any generated report?

**Comment by barttenbrinke** [comment]
Our mailer class currently also supports a options[:subject]. we could also bring that to the cli.

**Comment by anthias** [comment]
Sure. That would be valuable for us. Thanks for the great tool!

**Comment by barttenbrinke** [comment]
I've added a --mailsubject option in the last commit. Could you checkout the master and try it out?

**Comment by anthias** [comment]
Perfect. Works great. Thanks, jeff

**Comment by barttenbrinke** [comment]
No problem. It will be in the next gem release :)
