### ISSUE TITLE
Rails3 support?

### ISSUE THREAD

**Issue by plukevdh** [wvanbergen/request-log-analyzer#53]
Any current work in progress or thoughts on getting this up to date for Rails 3 logs? It seems there are errors in parsing for Rails3.

**Comment by barttenbrinke** [comment]
Is the new format stable? If so, it would be great you can get us a sample we could add to our test suite. With that we can build the support quite easily. bart@railsdoctors.com or github direct message.

**Comment by plukevdh** [comment]
Actually I'm not sure about that. also didn't realize you had 
    --format rails3
so I think I'm okay for now. Will update if I hear of finished log formats :)

**Comment by wvanbergen** [comment]
Note that the Rails 3 format file currently is very basic (at least compared to the Rails 2 file format). There is probably a lot more that we can parse and analyze from Rails 3 files. Patches are accepted :-)

**Comment by barttenbrinke** [comment]
I guess is that this is why the auto detect does not work :)?

**Comment by plukevdh** [comment]
i'd definitely be up for patching it, but since we're still in beta3, I'm not sure it'd be wise. once we hit rc1 maybe :) hoping soon!!
