### ISSUE TITLE
Does not analyze mysql logs

### ISSUE THREAD

**Issue by bublik** [wvanbergen/request-log-analyzer#55]
```
100609 13:32:12    1811 Query       SELECT     `hypervisors`.* FROM       `hypervisors` WHERE     (called_in_at >= '2010-06-09 12:31:12')
                   1811 Query       SELECT     `hypervisors`.* FROM       `hypervisors` WHERE     (called_in_at < '2010-06-09 12:31:12')
                   1811 Query       SELECT     `hypervisors`.* FROM       `hypervisors` WHERE     (called_in_at >= '2010-06-09 12:31:12')
```

**Comment by wvanbergen** [comment]
This format seems to be different than the slow query log we currently support. 

Is this a normal MySQL query log? What version are you using?

**Comment by barttenbrinke** [comment]
This looks like a rails query analyzer plugin and not the default mysql slow query log.

**Comment by wvanbergen** [comment]
Closing this issue for now. If somebody wants to support this format, please write a format file for it and send me a pull request.
