### ISSUE TITLE
Identify requests in mixed logfile by PID

### ISSUE THREAD

**Issue by acechase** [wvanbergen/request-log-analyzer#56]
Using Passenger instead of Mongrel makes the "one log file per port" suggestion on the Configure Logging wiki page even less tenable than with Mongrel since Passenger spins up app instances as needed. 

It is possible to put the PID in every logged line of output which would mean header and footer requests could be linked together in a mixed logfile setup. Has anybody done this before? Is there some configuration setting I may be missing to enable this type of behavior? I'm happy to take a stab at modifying the rails log file format processor myself but wanted to make sure I wasn't replicating somebody else's efforts.

**Comment by barttenbrinke** [comment]
If you parse a typical logfile for a day, how much requests get skipped?

**Comment by wvanbergen** [comment]
I think adding a PID-based "multiplexer" would be a good idea: i.e. first split the lines according to a PID found in every line, and then parse these lines according to the file format independently. 

Currently, RLA does not support something like this, although it is probably possible to get it to work with a very elaborate and hackish file format. Implementing this in the RLA core would probably be useful for other file formats as well*, but it will require adjusting some of the core RLA components.

(\* The Oink format would be much simpler to implement if something like this is in the core of RLA)

Please take a shot at this if you want to. Contact me if you have any questions.

**Comment by wvanbergen** [comment]
Maybe http://github.com/itsderek23 can give you some pointers, as he implemented the Oink file format.

**Comment by acechase** [comment]
I have one particularly slow request that receives approximately 25k hits a day and it looks like about 70% of those requests are being skipped. It's funny because the log analysis tells me the requests take 500ms (with a std dev of another 500ms) but I'm sure it's even slower than that since the longer the request takes the more likely interweaving with other requests will occur.

I like the "multiplexer" idea. I'll see if I can schedule some time to take a stab at implementing something along those lines (not too soon as I'm about to leave for a week of vacation :-). 

Thanks for the feedback. BTW, you guys have been doing a heck of a job with RLA, I really enjoy using it.

**Comment by itsderek23** [comment]
@acechase,

I implemented something very similar with the Oink parser format. It requires the syslog or Hodel3000 logger (the Hodel3000 is a lot easier to install in a Rails app) than syslog. The specs for Oink should show how it handles requests from multiple PIDs.

Look at step 2 here: https://scoutapp.com/plugin_urls/181-ruby-on-rails-monitoring/help_entries/351

Ideally, it'd also be nice to package Hodel3000 as a gem so the install is easier. 

Happy to help,

Derek (derek@scoutapp.com)

**Comment by acechase** [comment]
Thanks, Derek.

I thought about this problem for quite a while yesterday (and looked  and played with a couple implementation paths before coming to the solution I wound up putting into play. Unfortunately, the solution I wound up with does not fit perfectly with the more general flexibility of the RLA, but it fit my needs and I didn't have any additional time to invest (bummer).

The solution I ginned up is a simple pre-processor that I run on my log files to split them into multiple files based on pid. I then take that split output and feed it into RLA. I went with this approach for a couple reasons:
- I've already built out a decent amount of wrapping around the RLA, so adding one more step into my processing change was no big deal.
- It was simple.
- To implement the same functionality within the RLA framework at a well integrated level looks like it would take some doing.
- It actually feels a bit "cleaner" to me to separate out the different pid requests as a pre-process step in the spirit of unix tool chaining. Given the various different ways in which the PID may show up in the log file (Hodel3000 based output, Logging::Logger self defined line format, etc...) it's nice to have a self contained bit of code where those differences can be handled.

Here's my script:
http://gist.github.com/465693

I like the Oink approach. I also think there's an argument to be made for an additional parse-strategy in RequestLogAnalyzer::Source::LogParser. However, I have to move on to other issues so I'm going to roll with what I've got. I'd be happy to fill in a page on the wiki showing how I use the code I linked to above if anyone thinks that would be useful.

Cheers,
Andrew

p.s. Derek, Scoutapp looks dope!

**Comment by itsderek23** [comment]
@acechase,

No problem. For those interested in a single-file parsing strategy, Josh Nichols has created a fork of Hodel3000 to create a gem-able install. This is a great step to more accurate log parsing. 

Please give the gem install an upvote:

http://github.com/topfunky/hodel_3000_compliant_logger/issues/issue/2

**Comment by barttenbrinke** [comment]
About a year ago I write something like the multiplexer idea. It created a new analyzer if it encountered a logline it didn't expect (mismatch or other PID) and kept trying for X lines to complete the request for that analyzer. Turned out it was really slow and I had worse results than just dropping the interweaved requests. In our current setup it should fit quite easily in a fileformat.

**Comment by acechase** [comment]
To close the loop on this, here's some before and after numbers showing the improvement in analysis with log_splitter in play.

Before log_splitter:
Parsed lines:   815167
Skipped lines:  127209
Parsed requests:    322744

After log_splitter:
Parsed lines:   885548
Skipped lines:  6
Parsed requests:    443186

Also, it showed that our worst performing action was actually performing a full 30% slower than was previously being reported.

Once in production I needed to make one small adjustment to the script, I've updated the gist linked above to reflect that change.

**Comment by barttenbrinke** [comment]
We could transform this into some kind of PID preprocessor option. Stream the first PID directly to RLA and buffer any other PIDS into an array of some sort and flush them on end of file. Anyone want to build a patch for that :)?

**Comment by wvanbergen** [comment]
I would be more for a a separate application for this purpose. This is only necessary for Rails 2 logs (Rails 3 doesn't have this problem), and the approach requires you to fiddle with the Rails logger. If you're going to fiddle with it anyway, you can just as easy set it up to log to a separate file per PID.

**Comment by itsderek23** [comment]
Yeah - I'm not sure it's worth the effort to include this in RLA. It doesn't seem likely that a decent percentage of developers will go through this level of effort to do this. Also, while I haven't played with it yet, Rails 3 provides instrumentation hooks that might work well for performance reporting / log parsing.

**Comment by barttenbrinke** [comment]
We could provide it as a lib / rake task.. Or a mixin...

**Comment by barttenbrinke** [comment]
As I didn't want this to go to waste, I cleaned up the Gist somewhat and put it in the rails rla rake task. Also added Hodel and Syslog PID splitting support. In Master.

http://github.com/wvanbergen/request-log-analyzer/commit/a689cb1c76303052e824629ef4239b47ab622bfd

**Comment by acechase** [comment]
nice :)
