### ISSUE TITLE
Parsing issue w/Rails3 beta4 ('started' line definition timestamp parsing)

### ISSUE THREAD

**Issue by itsderek23** [wvanbergen/request-log-analyzer#57]
Hey guys,

I haven't had time to work up a patch, but I think there is an issue with the Rails3 format at the beta4 release parsing the timestamp in the 'started' line definition. 

The existing Rails3 file format expects the line as:

@Started GET "/queries" for 127.0.0.1 at 2010-02-25 16:15:18@

In my log, I see the line as:

@Started GET "/queries" for 127.0.0.1 at Wed Jul 07 09:13:27 -0700 2010@

It looks like the timestamp format is different:
2010-02-25 16:15:18 => Wed Jul 07 09:13:27 -0700 2010

**Comment by wvanbergen** [comment]
The Rails 3 format currently is in pre-beta state, especially compared to the Rails 2 format. I have little time available right now, so I will not be working on these issues before the final release of Rails 3.

If somebody else is willing to take this up, please do so. This issue is probably fixed with a simple patch.

**Comment by itsderek23** [comment]
Looking at this again, I'm curious why this change was made in Rails. It looks like the new logging format is just calling Time.now.to_s. Definitely not as concise as the previous format (and the same used in Rails 2).

**Comment by itsderek23** [comment]
Looks like it was made for performance reasons: http://github.com/rails/rails/commit/67a2d648d88f8520612fd7b01fcc7223290aac75

**Comment by barttenbrinke** [comment]
We're at BETA4 right now. Willem, could you provide some snippets of production logs?

**Comment by wvanbergen** [comment]
Some snippets:

```
Started GET "/dashboard.json" for 1.1.1.1 at Sat Jul 24 05:08:07 +0000 2010
  Processing by DashboardController#index as JSON
Rendered dashboard/index.json.erb (315.7ms)
Completed 200 OK in 334ms (Views: 325.0ms | ActiveRecord: 1.0ms)



Started GET "/custom_queries/6" for 1.1.1.1 at Sun Jul 25 19:25:44 +0000 2010
  Processing by CustomQueriesController#show as HTML
  Parameters: {"id"=>"6"}
Redirected to https://example/custom_queries/6/stored_queries/new
Completed 302 Found in 161ms



Started GET "/custom_queries/6/stored_queries/new" for 1.1.1.1 at Sun Jul 25 19:25:46 +0000 2010
  Processing by StoredQueriesController#new as HTML
  Parameters: {"custom_query_id"=>"6"}
Rendered stored_queries/_drilldown.html.erb (2.0ms)
Rendered stored_queries/_calculation.html.erb (0.6ms)
Rendered stored_queries/_metadata.html.erb (1.1ms)
Rendered stored_queries/_form.html.erb (29490.6ms)
Rendered layouts/_importing.html.erb (1.0ms)
Rendered layouts/_navigation.html.erb (6.5ms)
Rendered stored_queries/new.html.erb within layouts/default (29638.9ms)
Completed 200 OK in 29670ms (Views: 29647.4ms | ActiveRecord: 117.7ms)
```

**Comment by barttenbrinke** [comment]
itsderik: The removal of the inspect will have performance benefits, but the time.now.to_default_s is probably just a consistency change.

**Comment by barttenbrinke** [comment]
Rails3 RC2 in master
