### ISSUE TITLE
Wondering about adding a 95 percentile stat...

### ISSUE THREAD

**Issue by acechase** [wvanbergen/request-log-analyzer#58]
One of my colleagues was looking at our log analysis and pointed out that it would be very useful to have a 95 percentile stats column in addition to the current mean, stddev, min and max (or maybe just the a the second standard deviation as well as the first). The specific use case for such a feature is for actions with a profile similar to this one:

<pre>
HITS    SUM               MEAN  STDDEV  MIN MAX
85047   1h39m45s    0.07s   0.18s      0.01s    4.12s
</pre>

The current data is great, but as is it's hard to know how worried to be about  that 4 second max time. If that's happening only 1% of the time we're fine with it, if it's happening over 5% of the time it begins to feel more concerning. 

What's the thought on adding this type of sophistication to RLA? Better served by some other tool, or an appropriate addition?

**Comment by wvanbergen** [comment]
Sounds awesome, I would certainly accept a patch that adds this stuff.
Two gotchas:
- Can this be calculated during a single run in O(n)? All the other statistics only require a single pass.
- Can this be added to the report, especially in the console, without too much clutter?

**Comment by acechase** [comment]
I think the O(n) requirement is doable. I'll see if I can whip something up and test in console to see how the report looks.

**Comment by barttenbrinke** [comment]
If you build it, we will pull it :)

**Comment by wvanbergen** [comment]
If you're working on it, look at the update_statistics method in numeric value tracker (RequestLogAnalyzer::Tracker::NumericalValue). This is where the other statistics are calculated on the fly.

**Comment by acechase** [comment]
Maybe there's some clever way to do this, but as I'm looking into it I'm worried about meeting the O(n) runtime goal. I don't know of any clever way to calculate 95th percentile, only the standard method. There's two problems with the standard method: all results are kept around in memory until the final calculation; the final calculation requires an array sort. Here's a naive implementation of 95th percentile

<pre><code>
# In RequestLogAnalyzer::Tracker::NumericalValue
def update_statistics(category, number)
  ...
  if track_percentiles
    @percentile_tracker ||= Hash.new{|hash, category_name| hash[category_name] = [] }
    @percentile_tracker[category] << number
  end
  ...
end

def 95th_percentile(cat)
  percentile(cat, 95)
end

def percentile(cat, percent)
  return 0.0 if @percentile_tracker[cat].nil? || @percentile_tracker[cat].size == 0
  index = (@percentile_tracker[cat].size * (percent / 100.0)).round
  @percentile_tracker[cat].sort[index]
end 
</code></pre>


So, you can see from the above code, we'd introduce more memory requirements and an array sort.

**Comment by barttenbrinke** [comment]
http://en.wikipedia.org/wiki/Percentile

**Comment by wvanbergen** [comment]
Also note that normal distribution assumptions do not apply for this kind of data

**Comment by barttenbrinke** [comment]
I think the first question is: How should we calculate this?
I found 3 methods so far:

```
values = [ 2345, 3456, 5678, 7890, 5675, 3452, 56758, 2345, 234, 57788 ]
values.sort!
percentile = 0.80

# Calculate 1
dp = (values.length * percentile).to_i
p values[dp-1]

# Calculate 2
total = 0
values.each{|x| total += x}
p ((total/values.length)*percentile).to_i

# Calculate 3
slice = values[1..values.length-2] # 80 Percentile, so drop top and bottom of 10
slice_total = 0
slice.each{|x| slice_total += x}
p (slice_total/slice.length).to_i
```

Which gives me:
7890, 11649, 10949

Which one is correct or which one can be converted to O(n). The wikipedia has a few more options.

**Comment by barttenbrinke** [comment]
Definition #4:  The 95th percentile says that 95% of the time, the usage is at or below this amount. The AT here is interresting http://en.wikipedia.org/wiki/Burstable_billing

**Comment by acechase** [comment]
There's a fairly in depth treatment of the subject in the paper "Quantiles on Streams", available online at www.cs.ucsb.edu/~suri/psdir/ency.pdf. The paper starts with the following definition of quantiles:

Quantiles are order statistics of data: the φ-quantile (0 ≤ φ ≤ 1) of a set S is an element x such that φ|S| elements of S are less than or equal to x and the remaining (1 − φ)|S| are greater than x. This article describes data stream (single-pass) algorithms for computing an approximation of such quantiles.

Assuming that definition, I think the value from "Calculate 1" would be considered most correct. However, "Calculate 2" (and 3) could both be performed in O(n), since they don't rely on the values to be in sorted order. Of additional interest in the above example is that calculations 2 and 3 are sensitive to the actual size of each number in the values array whereas 1 is only sensitive to ordering.

**Comment by barttenbrinke** [comment]
2 and 3 however do have distribution assumptions which could be incorrect. For example:

```
values = [ 1,5,5,5,5,5,5,5,10 ]
values.sort!
percentile = 0.80

# Calculate 1
dp = (values.length * percentile).to_i
p values[dp-1]

# Calculate 2
total = 0
values.each{|x| total += x}
p ((total/values.length)*percentile).to_i

# Calculate 3
slice = values[0..values.length-2] # 90 Percentile, so drop top and bottom of 10
slice_total = 0
slice.each{|x| slice_total += x}
p (slice_total/slice.length).to_i
```

Which produces:
5, 4, 4

Looking at the ency.pdf definition, it defines 1 cuttoff point. So if we decide to leave the low 20% out in this example, the correct 80-percentile should be ([5,5,5,5,5,5,10].sum / 8) = 5.

As I presume requests do not conform to the normal distibution, i'll be reading the PDF tonight :).

**Comment by wvanbergen** [comment]
Distribution is certainly not normal. Shorter then average/median times will occur very infrequently, but extreme outliers to the other side are more common. The distribution becomes very skewed because of this. A set of times that I would consider as "common" could be:

```
[ 4, 3, 3, 4, 6, 4, 17, 5, 3, 3, 4, 4, 8, 5, 3, 6, 3 ]
```

What kind of numbers do we want to report on this set?

**Comment by barttenbrinke** [comment]
I would want the excesses to be filtered out. So the extremely fast and extremely slow cases should be removed. If we do a 80% on this, it would mean that (17*0.8) = 13 out of 17 items. So the slowest 2 and the fasted 2 should be dropped from the average.

**Comment by femto113** [comment]
For those interested I just did a patch that handles this sort of calculation for rails3 in our fork.  It uses the completely simple-minded approach of storing all observed values and sorting the array.  Unless you're processing logs with many millions of requests this is probably not going to be a problem in practice.

http://github.com/seomoz/request-log-analyzer/commit/51fe1d317a3e1f472e9cf2d32bb92e7fde893c2b

In re the discussion above I don't think rejecting outliers is needed for this type of tool.  Once you back away from relying on mean as a measure it's not really an issue.  You can and should pick a percentile to watch and optimize for, which one to use will vary by application type and what your service level commitment to your users is.  Big e-commerce sites like Amazon.com will watch four or five "9s" (the 99.99 or 99.999 percentile) but for your average web application is probably going to do fine in the one to two 9s range (90th to 99th percentile),

**Comment by femto113** [comment]
On another note--for processing streams or very large files within fixed memory you can sacrifice some precision and just use buckets with counts instead of storing individual values (the more buckets the more precise the result).  Because web requests aren't really that wide ranging (say 0 seconds to an hour at the extreme outside?) I'd guess 100 buckets in a log distribution over that range would be good enough for the vast majority of web sites.

**Comment by barttenbrinke** [comment]
Thats sounds like a good idea. I also think it should be possible to have 3 buckets with dynamic boundaries, but that probably won't be easy.

**Comment by femto113** [comment]
The general approach when precision matters is to use sampling to come up with  optimal buckets before processing the full data set, but I really think that's overkill here (plus sampling out of giant log files is likely to be expensive).

**Comment by barttenbrinke** [comment]
Dynamic bucket scaling attempt one:
Because we pretty much now the range of normal requests (0-1000ms) we can use for example 100 buckets, and then scale to (0-2000ms) if needed.

```
values = [1,2,3,4,5,6,7,8,9,10]

buckets = [0, 0, 0, 0, 0]
max_resolution = 5
devide = 1

values.each do |v|
  if v > max_resolution
    increase_factor = 2 # Should be 2 or more, depending on the size of v

    max_resolution = max_resolution * increase_factor
    devide = devide * increase_factor

    # Rescale current bucketss
    new_buckets = [0,0,0,0,0]
    buckets.each_with_index do |r, index|
      new_buckets[index/increase_factor] += r
    end

    buckets = new_buckets
  end

  buckets[(v/devide)-1] +=1

end

p buckets
```

**Comment by wvanbergen** [comment]
This approach is really dependent on the order of the requests:

<pre><code>
bucketize([1,2,3,4,5,6,7,8,9,10])
=> [2, 2, 3, 2, 1]

bucketize([1, 4, 5, 2, 9, 7, 8, 10, 3, 6])
=> [3, 1, 3, 2, 1]

bucketize([10, 4, 5, 2, 9, 7, 8, 1, 3, 6])
=> [2, 2, 2, 2, 2]
</code></pre>


Also, what exactly do you want to report based on these buckets?

**Comment by femto113** [comment]
You'll probably get fine results  just using log buckets.  If you set the range to go from 10e-5 or 1/100000 seconds (10 usec) to 10e5 or 100000 seconds (10**5 or about 1 day) you can easily calculate the right bucket for a given value as follows:

```
bucket_number = ((Math.log10(value) + 5) * 10).round
```

The 5 here is the exponent for lower bound of the range, the 10 here is the number of buckets (100) divided by the top exponent minus the lower exponent (5 - -5 or 10).  A general algorithm would be

```
range_min = 1.0/100000
range_max =  100000
num_buckets = 100
lower_exp = Math.log10(range_min).round
upper_exp = Math.log10(range_max).round
bucket_number = ((Math.log10(value) + (-lower_exp)) * (num_buckets / (upper_exp - lower_exp)).round
```

**Comment by femto113** [comment]
You can think of the buckets as just a run-length compressed version of the values array.  You could either reconstruct the values array from the buckets at the end and use the existing median and percentile logic or use some slightly fancier percentile logic that iterated over the bucket counts until it got to the desired percentage of the total count.

**Comment by barttenbrinke** [comment]
You should think of the buckets as a frequency graph:

```
  [3, 1, 3, 2, 1]

# #
# ##
#####
```

**Comment by wvanbergen** [comment]
Aha, interesting! Can somebody whip up a patch that integrates this approach in RLA?

**Comment by barttenbrinke** [comment]
Working on it, but snowleopard completely trashed my ruby env, so at the moment testing is impossible :(

**Comment by barttenbrinke** [comment]
I've got something that is sortof working. I'm not sure if what it is doing now is correct or not :). Should I push it and break the build so you guys can look at it, branch it, diff it or gist it?

**Comment by wvanbergen** [comment]
In order of my preference:
1. Branch
2. Fork
3. Diff
4. Gist
5. Punchcards

**Comment by barttenbrinke** [comment]
http://github.com/wvanbergen/request-log-analyzer/tree/percentile

**Comment by wvanbergen** [comment]
See my comments on the commit.

**Comment by barttenbrinke** [comment]
http://github.com/wvanbergen/request-log-analyzer/commit/9833e1503cae0e354e5ab461818ef9131b8d53f8

**Comment by wvanbergen** [comment]
My simplified attempt: http://gist.github.com/563750

Please test and tell me your findings.

**Comment by barttenbrinke** [comment]
wow :)

**Comment by wvanbergen** [comment]
The full implementation has been included in version 1.9.0

**Comment by barttenbrinke** [comment]
Yeah sorry, I probably should have mentioned that :)

**Comment by acechase** [comment]
Nice. I just upgraded -- looks great!
