### ISSUE TITLE
Create a database query tool

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#6]
Design and build a tool that can easily run queries on a request database that has been created with r-l-a.

**Comment by barttenbrinke** [comment]
Can't we just abuse irb for this ?

**Comment by wvanbergen** [comment]
Maybe, but it would be nice to get some helper functions that make this easier. The database structure requires a lot of JOINs.

**Comment by barttenbrinke** [comment]
Yeah, but you could just spawn an IRB with some method missing magic, right?

**Comment by wvanbergen** [comment]
Or offer something like Rails, which starts IRB with some libraries that are loaded when starting. You can specify requires on the irb command line.

**Comment by barttenbrinke** [comment]
That's what I meant :)

**Comment by wvanbergen** [comment]
I added an IRB console to inspect a database that initializes automatically for the upcoming r-l-a release (version 1.3). 

Start the console with: 
`request-log-analyzer console --database <DATABASE> --format <FORMAT>`

The following ActiveRecord classes will be available:
- Request
- Source
- Warning
- A class generated for every line type: :access -> AccessLine, :completed => CompletedLine, etc.
