### ISSUE TITLE
Rails 3 format doesn't parse exceptions / failed requests correctly

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#60]
The Rails 3 format does not parse exceptions correctly. I found three distinct possibilities for errors to appear:
- Unroutable requests; never reaches application code. Don't know if this will show up in production; it may just return a 404 error. This case is parsed correctly by the current implementation.

<pre><code>
Started GET "/raise/not_found" for 127.0.0.1 at Fri Sep 03 08:05:51 +0200 2010

ActionController::RoutingError (No route matches "/raise/not_found"):
  

Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (0.6ms)
</code></pre>

- Exception in controller code. This is not handled correctly, probably because of the "Completed" line.

<pre><code>
Started GET "/raise/controller" for 127.0.0.1 at Fri Sep 03 08:01:51 +0200 2010
  Processing by RaiseController#controller as HTML
Completed   in 3ms

RuntimeError (Testing):
  app/controllers/raise_controller.rb:46:in `controller'

Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.7ms)
Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (211.9ms)
Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (216.7ms)
</code></pre>

- Exception in template code. This one also isn't handled correctly, most probably because of the completed line.

<pre><code>
Started GET "/raise/template" for 127.0.0.1 at Fri Sep 03 08:03:59 +0200 2010
  Processing by RaiseController#vc as HTML
Rendered raise/template.html.erb within layouts/default (0.3ms)
Completed   in 6ms

ActionView::Template::Error (Testing):
    1: <% raise 'Testing' %>
  app/views/raise/template.html.erb:1:in `_app_views_raise_template_html_erb__669184355_2184051140_0'

Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.7ms)
Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (140.8ms)
Rendered /Users/willem/.rvm/gems/ree-1.8.7-2010.02/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (145.7ms)
</code></pre>

**Comment by sozialhelden** [comment]
I see this in my production log file too:
Started POST "/nodes" for 79.252.134.11 at Sun Aug 07 18:24:02 +0200 2011
  Processing by NodesController#create as _/_
  Parameters: {"node"=>{"lon"=>"13.408594069560131584", "name"=>"Lolas", "wheelchair"=>"unknown", "type"=>"bar
", "lat"=>"52.53494717737281536"}}
Completed   in 3ms

The request is not handled correct. It doesn't seem to end up in the controller action. It just finishes the request. Is there a way of tracking this down?

Cheers, Christoph

**Comment by wvanbergen** [comment]
Not sure, haven't looked into this in a while. Your log snippet doesn't seem to contain any information about an exception, which will make it impossible to parse. Also unfortunate: Rails keeps changing its log format slightly.
