### ISSUE TITLE
bug in rails3 format when active record is disabled

### ISSUE THREAD

**Issue by dcu** [wvanbergen/request-log-analyzer#64]
this is the correct format which is not matched by request-log-analyzer

```
Completed 200 OK in 364ms (Views: 31.4ms)
```

**Comment by wvanbergen** [comment]
This line parsed fine with me in the latest request-log-analyzer. What version are you using? And can you provide the log fragment that contains the entire request?

**Comment by barttenbrinke** [comment]
Same here :)

**Comment by wvanbergen** [comment]
Closing this issue until we have more info.
