### ISSUE TITLE
Work with RSpec2?

### ISSUE THREAD

**Issue by plukevdh** [wvanbergen/request-log-analyzer#65]
How much trouble would it be to switch to RSpec2?

**Comment by wvanbergen** [comment]
Probably not that much. I already converted another project to RSpec2 without many problems. It only requires some renames and configuration changes here and there; all the specs themselves can remain unmodified.

**Comment by wvanbergen** [comment]
Now upgraded

**Comment by plukevdh** [comment]
Fantastic, that was quick.
