### ISSUE TITLE
Modding - cli parsing issue

### ISSUE THREAD

**Issue by plukevdh** [wvanbergen/request-log-analyzer#66]
I'm trying to add an option that takes multiple params using the `:multiple => true` option, however it doesn't seem to parse any arguments but the first one.

I'm looking at the example set by the --aggregator option, which, doesn't actually show up in the printed documentation from the -h option and is not among the spec tested options. Is there a reason for that?

**Comment by wvanbergen** [comment]
No, the documentation and help are just incomplete. I would like to move to a library for handling the CLI stuff instead of our own handling, e.g. thor. Unfortunately, it is most likely not possible to build something like that without breaking backwards compatibility.

**Comment by wvanbergen** [comment]
The simplest option I found with multiple parameters is `--reject`:

```
command_line.option(:reject, :multiple => true, :parameters => 2)

# ...

if options[:reject]
  options[:reject].each do |(field, value)|
    controller.add_filter(:field, :mode => :reject, 
           :field => field, :value => value)
  end
end
```

**Comment by plukevdh** [comment]
I guess that's an issue for version 2 then huh?

I'd use the `:paramters` option except that the change I'm trying to add takes either 1 or three params. Is multiple supposed to eat params until it hits the next --? I thought this was originally the case but maybe the specs for this have changed?

**Comment by wvanbergen** [comment]
I don't think this is possible now. Your options:
- Modify the command line handler to allow stuff like this.
- Use two different command line options.

I have created some issues about stuff we want to put in a 2.0 version. One is about how to handle command line options. Feel free to add you comments to it.

**Comment by wvanbergen** [comment]
I am closing this issue because this is not going to be fixed in the 1.x versions (unless you do it yourself :).
