### ISSUE TITLE
Mongodb inserter

### ISSUE THREAD

**Issue by jstemmer** [wvanbergen/request-log-analyzer#69]
I am thinking of creating a mongodb inserter to store the requests and I'm looking for some advice on implementing this. I'm only just starting to get familiar with the code and I'm looking for a way to extend the functionality by providing an extra option on the commandline like the --database option without having to modify (much of) the core code. 

Using just the api and gem I would have to duplicate all the commandline handling etc. I guess what I'm looking for is some way of hooking into the gem, adding an custom aggregator. Do you have any thoughts or advice on this?

**Comment by wvanbergen** [comment]
At this moment the best way would be to fork the project and implement the feature in the code itself.

We would like version 2.0 to be able to support plugins that can handle this stuff. I've opened several 2.0 tickets with ideas. Feel free to chip in with your own ideas and experience.

**Comment by nickhoffman** [comment]
Hey guys. Has any progress been made on a MongoDB inserter?

**Comment by wvanbergen** [comment]
Nope. Feel free to pick it up if you're interested.
