### ISSUE TITLE
2.0 ideas: allow plugins

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#70]
Allow request-analyzer to load gem based plugins.

```
gem install request-log-analuzer-mongo
request-log-analyzer --plugin mongo production.log
request-log-analyzer list-plugins
```

Some issues to resolve:
- How to load and initialize plugins?
- Providing hooks that plugins can use to do their stuff.
- Plugins should be able to specify command line options.

**Comment by barttenbrinke** [comment]
I would rather have the possibility of mixing plugins so, request-log-analyzer --filter PLUGIN1 --aggregator PLUGIN2 production.log
