### ISSUE TITLE
2.0 ideas: provide a Rails 3 Railtie as plugin

### ISSUE THREAD

**Issue by wvanbergen** [wvanbergen/request-log-analyzer#74]
Improved Rails integration should be available by providing a Railtie. The best way to offer this is as a plugin (e.g. request-log-analyzer-railtie) so that we do not have a dependency on Rails by default.

**Comment by wvanbergen** [comment]
- rake tasks
- capistrano task to run on server
- generators
- default place to store configuration and file format
- default place to archive reports

**Comment by mikhailov** [comment]
I have this capistrano task:

```
desc "Request-log-analyzer"
task :rla, :roles => :app do
  run "cd #{current_path}; bin/request-log-analyzer #{shared_path}/log/#{rails_env}.log" do |channel, stream, data|
    puts "#{data}"
    break if stream == :err
  end
end
```
