### ISSUE TITLE
Continous Parsing of Logs to be appended into database

### ISSUE THREAD

**Issue by davidchua** [wvanbergen/request-log-analyzer#8]
Is there anyway to do continuous logging of *.logs such that after an inital parse of a log into a sqlite3 database, RLA would monitor the log and append the changes since the last parse date into the database? 

That way old logs even after it gets rotated, will still be recorded into the database.

**Comment by wvanbergen** [comment]
You can emulate behavior like this using the UNIX tail command, and piping the result through RLA:

tail -f log/production.log | request-log-analyzer --database log/requests.db -
(don't forget the dash on the end to indicate that you are parsing the standard input)

However, this will create a new database, so it is not possible to "resume" to a previous database file. Adding that feature would be nice indeed. :-)

**Comment by wvanbergen** [comment]
Continuous parsing will require to check the database schema, to see whether the old structure is compatible with the file that is being parsed.

**Comment by barttenbrinke** [comment]
I have a rails logger here that just logs everything to the database instead of to file. I'll see if it is easily adaptable

**Comment by wvanbergen** [comment]
I think directly adding request to the database from Rails is outside the scope of RLA. Moreover, I doubt that this approach will work to make it compatible with other file formats.

IMHO, a better approach is to simply parse the logs and append it to the existing database file. However, before we can add data, we need to check whether the database schema is compatible, which depends on the log format specification. Currently, the old database file is simply deleted at the beginning, wiping all old data.

As a bonus, we could detect if the parsed request data is already inserted into the database to avoid duplicate data. This is a little bit more complex on first sight, as requests do not have a unique identifier.

**Comment by barttenbrinke** [comment]
That sounds like a major performance hog

**Comment by wvanbergen** [comment]
If you mean the last idea: without some kind of a unique index, indeed. However, maybe a unique index using the timestamp, IP address and controller/action of the request might be acceptable.

**Comment by wvanbergen** [comment]
Another idea: store the filenames (including last modified date) that have been parsed and iserted into the database in a separate table to keep track of what has been parsed and what not.

**Comment by danlucraft** [comment]
Yes to your last comment wvanbergen.

**Comment by wvanbergen** [comment]
Apparently, danlucraft started working on this

**Comment by wvanbergen** [comment]
Status update:
- A database will not be cleared when parsing starts (unless `--reset-database` is given as an option).
- Parsed files are now stored in the `sources` table, including the filesize and mtime at the moment of parsing.

Still to do:
- Check if the database schema still matches the file format
- Allow resuming by skipping the first `n` bytes of a file.

**Comment by wvanbergen** [comment]
I have created new issues for the outstanding TODOs, but basically the continuous parsing works now.
