### ISSUE TITLE
median request time

### ISSUE THREAD

**Issue by ghazel** [wvanbergen/request-log-analyzer#81]
Average can be wildly skewed by outliers. It would be very nice to have median request time reported.

**Comment by wvanbergen** [comment]
This is actually really easy to implement because we already keep track of all percentiles. However, we do not really have that much screen estate left, so adding another column may not be the best solutions. Any ideas?

**Comment by ghazel** [comment]
Well, I'd personally prefer it over "mean" entirely, but I also use the yaml output to graph in munin, so if it didn't appear in the text output you're talking about that would be fine for my case.

**Comment by barttenbrinke** [comment]
What will the difference be between median and 95th percentile? I understand the math, but what do you really need it for in real file?

**Comment by ghazel** [comment]
Well, the trouble with average is that it does not reflect a real page load time. If all samples are 30ms but one is 10000ms, the average will be somewhere in the middle, when no one actually saw that load time. If the 95th percentile picks a real measured time under which 95% of samples fall, that would be fine.

**Comment by barttenbrinke** [comment]
The current implementation removes the outliers.. so it pretty much does what you want. You can even tweak the percentage.

**Comment by ghazel** [comment]
Hm, ok. How do I get at this in the yaml? I'm running 1.6.2, and all I see are [sum, mean, min, max, hits, sum_of_squares]

**Comment by barttenbrinke** [comment]
I think it's has not been added to the YAML yet. Look at the text report and use that to put add a 95th percentile item to the yaml.

**Comment by barttenbrinke** [comment]
Fixed in master
