### ISSUE TITLE
w3c log format?

### ISSUE THREAD

**Issue by zfben** [wvanbergen/request-log-analyzer#84]
I have some w3c log format file, but I don't know how to use rla to prase them, who could help me, thx?

**Comment by wvanbergen** [comment]
Request-log-analyzer cannot parse this file format out of the box. You will need to write your own file format for it. Pointers on how to do that can be found here: https://github.com/wvanbergen/request-log-analyzer/wiki/Creating-your-own-file-format-definition 

If you have a sample log snippet, I could give you some more pointers.

**Comment by barttenbrinke** [comment]
http://www.microsoft.com/technet/prodtechnol/WindowsServer2003/Library/IIS/676400bc-8969-4aa7-851a-9319490a9bbb.mspx?mfr=true

**Comment by barttenbrinke** [comment]
https://github.com/wvanbergen/request-log-analyzer/commit/2bbe2fbb129175671b7f809854db3a9eaf6fabbd

Could you test it out and open a ticket if something is not working?
