### ISSUE TITLE
Diversify reports per HTTP method

### ISSUE THREAD

**Issue by romk** [wvanbergen/request-log-analyzer#87]
For analysis of a ReSTful application it would be useful to report each HTTP method separately. Typically some methods (PUT, POST) take much longer to process that others (HEAD, GET) and should be analyzed separately.

I now pipe the log files through sed to prepend the HTTP method to the URL.

**Comment by wvanbergen** [comment]
You can easily do that using the --select option:

   request-log-analyzer log --select http_method GET

What kind of log file are you trying to analyze?

**Comment by romk** [comment]
In my understanding that would filter out the other requests.

The intention is to report all requests, but report them separately.

I would attach a sample of the report i'm now creating if only I knew how to attach an image...

Here's a snippet, note that the POST requests all end up on top. If I would combine them with the GET requests on the same URL which are much faster and more numerous, these requests would not show up on top of the 'average' list.

REQUEST DURATION - BY MEAN  HITS    SUM MEAN    STDDEV  MIN MAX 95 %TILE
POST:/asyws/rest/customers/{customerId}/orders/{orderId}    4   17.07s  4.27s   4.62s   1.18s   11.14s  1.17s-11.14s
GET:/asyws/rest/customers/{customerId}/profile_settings 1   1.79s   1.79s   0.00s   1.79s   1.79s   1.77s-1.83s
POST:/asyws/rest/customers/{customerId}/carts/{cartId}  31  15.30s  0.49s   1.41s   0.15s   8.07s   0.15s-8.07s

**Comment by wvanbergen** [comment]
This can best be solved by writing a custom file format. Instead of just one report item, you can add a report item for every HTTP request method, by setting an :if-condition that only returns true for the correct HTTP method.

See the project's wiki for more information on writing your own file format.
