### ISSUE TITLE
Aggregate ReSTful requests per resource

### ISSUE THREAD

**Issue by romk** [wvanbergen/request-log-analyzer#88]
For analysis of ReSTful requests it would be useful to aggregate requests per resource because all requests to that resource can be expected to take similar time.

For example, the following requests are now listed separately but should be considered the same:
GET /rest/customer/001
GET /rest/customer/002

I now pipe log files through sed to replace the path parameter values with a fixed string, like:
GET /rest/customer/{customerId}

**Comment by wvanbergen** [comment]
The Rails file format already does this correctly. For other file formats it is not possible to do these substitutions reliably. The best thing that you can do is build a custom file format for your particular app or framework that handles it correctly.

**Comment by romk** [comment]
Ok, makes sense, sed is also fine for this.

**Comment by wvanbergen** [comment]
Like I said, it seems that you would profit a lot by writing a custom file format for your application. You will need to write some simple Ruby code, but it is the easiest way to customize rla's reports to the specifics of an application.
