### ISSUE TITLE
Rails3 log parser doesn't understand "processing" lines with no format

### ISSUE THREAD

**Issue by mackuba** [wvanbergen/request-log-analyzer#92]
Sometimes, if http accept header is set to something strange, Rails prints an empty format in the "processing" line, e.g.:

```
Processing by ProfilesController#show as 
```

This is displayed as "#." in the report because the regexp doesn't match the line at all. A better way to handle this would be to still parse the controller and action.

This should fix it:

```
- line.regexp = /Processing by ([A-Za-z0-9\-:]+)\#(\w+) as ([\w\/\*]+)/
+ line.regexp = /Processing by ([A-Za-z0-9\-:]+)\#(\w+) as ([\w\/\*]*)/
```

**Comment by wvanbergen** [comment]
Fixed on master.

**Comment by barttenbrinke** [comment]
Thanks! Fixed in Master.

**Comment by wvanbergen** [comment]
Bart: stop double fixing issues :P

**Comment by wvanbergen** [comment]
I git-push-origin-master---force'd your patch into oblivion. That'll teach you ;)

**Comment by barttenbrinke** [comment]
Push first, ask questions later :)
