### ISSUE TITLE
Nothing parsed with delayed_job21

### ISSUE THREAD

**Issue by osaris** [wvanbergen/request-log-analyzer#94]
Hello,

I'm running dj 2.1.4 and request-log-analyzer 1.10.0. When I parse the following dj log :

```
2011-03-10T09:00:28+0100: [Worker(delayed_job host:srv01.imagineapp.com pid:3369)] Convocation#send_emails completed after 2.8305
2011-03-10T09:00:28+0100: [Worker(delayed_job host:srv01.imagineapp.com pid:3369)] 1 jobs processed at 0.3502 j/s, 0 failed ...
```

with command :

```
request-log-analyzer delayed_job.log.1
```

I get :

```
Parsed lines:        1
Skipped lines:       1
Parsed requests:     0
Skipped requests:    0 
Warnings:            no_current_request: 1
There were no requests analyzed.
```

I've tried various of my dj logs but none works :-/

Regards,

Raphaël

**Comment by wvanbergen** [comment]
Can you post a more complete snippet?

**Comment by barttenbrinke** [comment]
What does this give you?
$ request-log-analyzer delayed_job.log.1 --format delayed_job_21

**Comment by osaris** [comment]
Today with following log :

```
2011-03-11T16:11:28+0100: [Worker(delayed_job host:srv01.imagineapp.com pid:3369)] Class#create_defaults completed after 0.0396
2011-03-11T16:11:29+0100: [Worker(delayed_job host:srv01.imagineapp.com pid:3369)] Class#confirmation_instructions completed after 0.7869
2011-03-11T16:11:29+0100: [Worker(delayed_job host:srv01.imagineapp.com pid:3369)] 2 jobs processed at 2.3783 j/s, 0 failed ...
```

I got the following output :

Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.10.0
    Website: http://railsdoctors.com

```
delayed_job.log.1:       100% [===============================================================================================================================================] Time: 00:00:00

Request summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Parsed lines:        2                    
Skipped lines:       2                    
Parsed requests:     0                    
Skipped requests:    0                    
Warnings:            no_current_request: 2


There were no requests analyzed.

Parse warnings
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Parsable lines were encountered without a header line before it. It
could be that logging is not setup correctly for your application.
Visit this website for logging configuration tips:
http://github.com/wvanbergen/request-log-analyzer/wikis/configure-logging


Need an expert to analyze your application?
Mail to contact@railsdoctors.com or visit us at http://railsdoctors.com.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Thanks for using request-log-analyzer!
```

**Comment by wvanbergen** [comment]
Apparently, your log does not contain the "acquiring lock" lines, which request-log-analyzer. I'm not sure if this is because of a setting or because the log format of Delayed::Job has changed (again).

**Comment by osaris** [comment]
I have no delayed_job configuration in my app so I suppose that this behaviour is standard and delayed_job has changed its logs format ?

**Comment by barttenbrinke** [comment]
Hmm.. I think we have three options:
1) Add third Delayed Job format
2) Remove First 2 DJ formats and add new
3) Drop DJ support.

Has someone informed DJ that we are having these problems?

**Comment by barttenbrinke** [comment]
Informed DJ, waiting for a response: https://github.com/collectiveidea/delayed_job/issues/220

**Comment by thoughtpunch** [comment]
Delayed Jobs has had the same log format for over a year now. Any chance someone will get around to this?

**Comment by barttenbrinke** [comment]
If you could fork it and send in a pull request, that would be awesome! I'm currently not using Delayed Job in any of my projects, so it is kind of hard for me to test / get log samples.
