### ISSUE TITLE
Inquiry: What does the red color of the bars in "Request distribution per hour" mean

### ISSUE THREAD

**Issue by bradland** [wvanbergen/request-log-analyzer#95]
I hate to open an issue for an inquiry, but I don't know of a mailing list. I frequently notice that the bars in the "Request distribution per hour" section of our reports are red [1], but I don't understand why. I tracked down the code the creates the red bars, but the ":treshold" parameter is set to a value I don't understand:

hourly_spread.rb:83-90

```
days = [1, timespan].max
output.table({}, {:align => :right}, {:type => :ratio, :width => :rest, :treshold => 0.15}) do |rows|
  @hour_frequencies.each_with_index do |requests, index|
    ratio            = requests.to_f / total_requests.to_f
    requests_per_day = (requests / days).ceil
    rows << ["#{index.to_s.rjust(3)}:00", "%d hits/day" % requests_per_day, ratio]
  end
end
```

fixed_width.rb:192-208

```
case column[:type]
when :ratio
  if width > 4
    if column[:treshold] && column[:treshold] < row[index].to_f
      bar = ''
      bar << characters[:block] * (width.to_f * column[:treshold]).round
      bar << colorize(characters[:block] * (width.to_f * (row[index].to_f - column[:treshold])).round, :red)
      row_values.push(bar)
    else
      # Create a bar by combining block characters
      row_values.push(characters[:block] * (width.to_f * row[index].to_f).round)
    end
  else
    # Too few characters for a ratio bar. Display nothing
    row_values.push('')
  end
else
```

This should probably make sense to me, but I'm an "infrequent" programmer, so I'm struggling to understand what the 0.15 threshold is for. 

Any insight you can provide would be really helpful, and thanks again for such a wonderful tool.

Any insight you can provide would be really helpful, and thanks again for such a wonderful tool :)

1 - Example of red bars: http://imgur.com/q2oSF

**Comment by wvanbergen** [comment]
0.15 = 15% of traffic. By default, you would expect 100% / 24 = ~4% traffic every hour if the traffic would flow to your app evenly. The 15% threshold is just to indicate the hours that gat a proportionally very high amount of traffic.

So, the 15% is simply a value that is chosen by us, it could just as well have been 10% instead

**Comment by bradland** [comment]
Thanks so much for the quick response, Willem. I really appreciate it :)
