### ISSUE TITLE
problem with postgres 8.3 log file

### ISSUE THREAD

**Issue by yenhsiac** [wvanbergen/request-log-analyzer#96]
sample postgres log lines:
1 single line statement
mc-vas-1.xxx.com(37879)-musubi-2011-03-06 06:30:40 PST: LOG: duration: 37900.371 ms statement: SELECT message.id, message.uid, message.temp
late, message.linkback, message.from_address, message.to_address, message.environment, message.deliver_after, message.status, message.error FROM message
WHERE (((message.status) = ('pending')) AND ((message.deliver_after) <= ('2011-03-06 06:30:02'))) ORDER BY message.id DESC
1. we also have some multiline log statement:
   mc-vas-13.xxx.com(60284)-musubi-2011-03-18 13:40:27 PDT: LOG:  duration: 1374.606 ms  statement: select \* from sponsored_listing where upper(city) = 'WAUKEGAN' and upper(state) = 'IL'
                       and status = 'active'
                       and to_tsvector( keyword )  @@ to_tsquery( 'CLUB|FOOD') 
                       order by ts_rank(to_tsvector( keyword ),
                        to_tsquery('CLUB|FOOD' ) ) 
# 

request-log-analyzer postgresql-8.3-main.log.1 --format postgresql
Request-log-analyzer, by Willem van Bergen and Bart ten Brinke - version 1.10.1
Website: http://railsdoctors.com

postgresql-8.3-main.log: 100% [========================================================================================================] Time: 00:06:41

Request summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Parsed lines: 1059106
Skipped lines: 1059106
Parsed requests: 0
Skipped requests: 0
Warnings: teaser_check_failed: 1821129, no_current_request: 1059106

There were no requests analyzed.

Parse warnings
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Parsable lines were encountered without a header line before it. It
could be that logging is not setup correctly for your application.

**Comment by barttenbrinke** [comment]
At the moment we only support Postgres 8.3.7. Which version are you on exactly?

**Comment by yenhsiac** [comment]
PostgreSQL 8.3.3 on x86_64-pc-linux-gnu, compiled by GCC cc (GCC) 4.2.3 (Ubuntu 4.2.3-2ubuntu7)

**Comment by barttenbrinke** [comment]
Could you upgrade in your staging environment to see if it works?
