### ISSUE TITLE
IPv6 not supported

### ISSUE THREAD

**Issue by romk** [wvanbergen/request-log-analyzer#98]
An IPv6 address in the logfile could look like this:
0:0:0:0:0:0:0:1 - - [24/Mar/2011:00:01:03 -0500] "GET ....
Such lines are not recognized as requests

**Comment by wvanbergen** [comment]
What file format are you using?

**Comment by romk** [comment]
pattern="%h %l %u %t &quot;%r&quot; %s %b &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; %D000"

--apache-format "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"

**Comment by wvanbergen** [comment]
Fixed on master.
